### ISSUE TITLE
Método cep não pode ser resolvido

### ISSUE THREAD

**Issue by salgueiroso** [filipedeschamps/cep-promise#100]
Estou enfrentando problemas quando chamo a função **cep()** no angular. Peço desculpas pela ignorância de não ter conseguido resolver, sou novo no mundo do NodeJs e NPM.
O erro retornado é o seguinte:
**`ERROR TypeError: cep_promise_1.default is not a function`**

Estou usando as seguintes versões:
`Angular CLI: 1.6.1
Node: 8.9.3
Angular: 4.4.6
cep-promise: 2.0.6`

Quando crio um novo app e instalo o cep-promisse, tudo funciona normalmente.
Mas no projeto atual ele funcionava normalmente a meses, até eu rodar o npm install, ontem, desde então não funciona mais.

Estou importando o cep-primise da seguinte forma:
**`import {default as cep} from 'cep-promise';`**

Abri os fontes do arquivo `dist/cep-promisse.js` e alterei a linha **`99`** da seguinte forma:
**`module.exports = exports['default'];`**
Alterei para
**`module.exports = exports;`**

Desde então tudo voltou a funcionar normalmente.
Creio que o problema esteja no arquivo de módulo **`index.d.ts`**, na declaração da exportação do método cep. Tentei alterar essa declaração, mas nenhuma das alterações resolveu o problema.
Suspeito que seja um problema causado por versão de dependência do cep-promise, não dos fontes dele. Mas todos os pacotes que o cep-promise depende estão instalados com suas versões mínimas suportadas.

Alguem teria uma orientação de como resolver isso sem precisar alterar os fontes do componente?

**Comment by lucianopf** [comment]
Opa irmão, desculpa a demora pra responder, manjo pouquíssimo de Typescript e nada de Angular. 😢 

Mas vou invocar aqui algumas pessoas que podem te ajudar nessa missão @salgueiroso ! ^^

@petronetto @claytonsilva 🔥 🚀

**Comment by lucianopf** [comment]
@filipedeschamps agora é com vc! hehehe

Tem como subir pro NPM a versão mais recente?

**Comment by petronetto** [comment]
Opa, foi mal a demora... Muitas notificações semana passada e essa passou batida... Mas pelo que vi o @claytonsilva resolveu... Só falta atualizar na doc.

**Comment by salgueiroso** [comment]
Tranquilo @petronetto resolveu mesmo

**Comment by filipedeschamps** [comment]
@lucianopf só pra confirmar, mesmo com os últimos merges, é subir uma versão patch, correto?

**Comment by lucianopf** [comment]
Isso mesmo @filipedeschamps ! =D

🚀

**Comment by filipedeschamps** [comment]
Feito, vocês são sensacionais!!! 👍 👍 👍
