### ISSUE TITLE
Exceção na importação do cep-promise angular2

### ISSUE THREAD

**Issue by KellysonRN** [filipedeschamps/cep-promise#107]
Olá, não estou conseguindo fazer a importação do cep-promise na minha aplicação angular2

Estou adicionando o seguinte trecho:  `import { default as cep } from 'cep-promise';`

e quando inicio a aplicação o console me retorna: 
> Module ''cep-promise'' has no exported member 'default'.

Alguém já passou por isso ?

**Comment by lucianopf** [comment]
Rapaz, dando uma olhadinha no arquivo gerado [aqui](https://unpkg.com/cep-promise@2.0.7/dist/cep-promise.js), vc vê que no final o que ta sendo exportado na verdade não é um objeto, e sim um valor, então a meu ver a importação correta se daria com `import cep-promise from 'cep-promise'` (se vc tiver no ambiente node).

Mas como eu sou um asno pra Angular e seu ecossistema eu escolho voce @claytonsilva !
Vai, chicote de vinha!!!

😂

**Comment by KellysonRN** [comment]
@lucianopf consegui executar minha aplicação fazendo o downgrade 2.0.7 para 2.0.6. Aparentemente algo na versão mais recente não funcionou na minha aplicação angular.

**Comment by lucianopf** [comment]
Rapaz, aí vc embolou minha cabeça! 🤔 

Este são os arquivos `cep-promise.js` em 2.0.6 e 2.0.7 a exportação é identica! 🤔 

![screen shot 2018-01-25 at 7 02 28 pm](https://user-images.githubusercontent.com/8251208/35412142-5f05b1b0-0202-11e8-8732-b0b1ec8ff182.png)

@KellysonRN vc ta usando isso em que environment? Isso é shippado pro Browser ou permanece no Node só no servidor?

**Comment by claytonsilva** [comment]
huehuaeahueahue beleza @lucianopf!

então @KellysonRN, quando colocamos suporte a typings simplificamos ao máximo o import do módulo, de forma que não precisa de colocar `{ default as cep }` , só colocar assim:

`import * as cep from 'cep-promise';`
e consumir ... `{ default as cep }` era cagadinha de typings mal feito

**Comment by lucianopf** [comment]
Da ausência de types hahahaha

**Comment by KellysonRN** [comment]
Aaah @claytonsilva está explicado ! Acho que cabe um update la no README do repositório. =)

**Comment by claytonsilva** [comment]
Boa!
