### ISSUE TITLE
Cep is not a function no Angular 5

### ISSUE THREAD

**Issue by rdorta** [filipedeschamps/cep-promise#112]
Primeiramente parabéns pelo projeto.

Ao utilizar com Angular 5, após a instalação via npm:

Utilização:
import * as cepFunction from 'cep-promise'

cepFunction('18110-210').then(console.log);

ERRO:
ERROR TypeError: cepFunction is not a function

**Comment by lucianopf** [comment]
Typescript man @claytonsilva, eu invoco vc! 😄

**Comment by claytonsilva** [comment]
:D invocado, tá na minha roadmap do dia já :D

**Comment by gabrielggd** [comment]
Parabéns pelo projeto e pela atenção
Eu consegui fazer funcionar no Angular5 usando:
`import * as cepPromise from 'cep-promise/dist/cep-promise-browser'`

**Comment by claytonsilva** [comment]
Pessoal fiz uns testes com angular 5 e parece que teve atualização do typescript que acabou resolvendo um velho problema.

Já mandei a pr pra ajustar a chamada do cep com typings mais `arrumadinho`
https://github.com/filipedeschamps/cep-promise/pull/113

**Comment by claytonsilva** [comment]
@lucianopf malz demora :(

**Comment by lucianopf** [comment]
Hahaha, rlx mano, aqui é open, contrib tem que vir quando tem tempo msm! 😂 👍

**Comment by lucianopf** [comment]
A issue ainda é válida @rdorta ? 🤔  
(não tive problemas utilizando a lib com a versão mais recente do TypeScript)

**Comment by rdorta** [comment]
Confesso que não utilizei mais. Vou tentar reproduzir novamente
