### ISSUE TITLE
Dúvidas e Sugestões (2018)

### ISSUE THREAD

**Issue by PauloBoaventura** [filipedeschamps/cep-promise#116]
Este código esta funcionando em PHP 5, 5.6, 7.0, 7.1 ou até mesmo em 7.2 ?
São muitas dúvidas e nada pessoal... (Já deixo claro)
Este código esta nas normativas novas dos correios (2017) e que pelo visto já existe novas normativas em (2018)...
Bom, este não é o único que visualizamos que aparentemente esta tudo correto.
Mas, tenho que ser este USUÁRIO questionador, já que estamos enfrentando tantos problemas seja eles em PHP, AJAX ou qualquer impulso anterior á 2017.
E assim vem as dúvidas...

Gostaria de saber se podemos implementar este código em outras ferramentas e até mesmo em outas plataformas... 

Espero que tenhamos uma resposta satisfatória e um UPGRADE. (O que neste notamos que o upgrade é notavel).

**Comment by filipedeschamps** [comment]
@PauloBoaventura tudo bem?

Não pude compreender muito bem essa issue. No backend o código roda apenas com Node.js.

Já no frtontend roda normalmente como uma biblioteca JavaScript, ou seja, nesse caso você poderá utilizar com qualquer backend ou plataforma.

Se você quiser analisar os detalhes de implementação e reimplementar em outra linguagem, fique a vontade.

Espero ter entendido sua dúvida.

**Comment by PauloBoaventura** [comment]
Olá @filipedeschamps e @petronetto 

Sim o que preciso efetivamente é que funcione no Magento 1.9 ou 2.1
E exato eu abri diversos issue como citou... 
E estou em busca, tanto de uma resposta dos desenvolvedores quanto uma solução... 

Alguma sugestão...

Abs!

**Comment by petronetto** [comment]
@PauloBoaventura como o @filipedeschamps mencionou anteriormente, para backend a lib é para Node, mas no frontend você pode usá-la normalmente.

**Comment by filipedeschamps** [comment]
@PauloBoaventura acredito que suas dúvidas tenham sido esclarecidas, qualquer coisa abrimos de volta a issue.

**Comment by PauloBoaventura** [comment]
Irei fazer testes!
Obrigado pela ajuda!!!
