### ISSUE TITLE
Erro ao utilizar no Angular 6

### ISSUE THREAD

**Issue by CarolPC** [filipedeschamps/cep-promise#117]
Fiz o npm install e estou utilizando o Angular 6.

Quando vou subir o projeto, já tendo importado o package em um componente eu recebo 2 erros no console. 

<img width="499" alt="screen shot 2018-06-08 at 12 27 26" src="https://user-images.githubusercontent.com/7128885/41166701-563161c8-6b17-11e8-93a9-314a1694806e.png">

**Comment by lucianopf** [comment]
Eitcha maravilha... parece que temos uma dependência fujona aí! hehehe
Amanhã vou tomar um tempinho pra resolver isso @CarolPC , valeu!! =D

**Comment by lucianopf** [comment]
Então @CarolPC algo bem bizarro ta acontecendo! 🤔 

O problema não tá diretamente no `cep-promise` mas nas dependências, e aparentemente elas tão tendo problemas em dar `require` nos módulos padrões do Node como:
- https://nodejs.org/api/timers.html#timers_timers
- https://nodejs.org/api/stream.html#stream_stream

Teria como vc me mandar as specs do seu ambiente pfv pra tentar reproduzir melhor?
- runtime (é node mesmo?):
- OS:
- Versão do runtime:
- Se possível, descrever o processo de build:

**Comment by CarolPC** [comment]
Runtime: node 9.6.1
OS: macOS Sierra
Typescript: 2.7.2

E a falha acontece quando eu rodo o ng serve no Angular.

**Comment by lucianopf** [comment]
Sumonando nosso mestre em TS pra dar uma luz aqui! hehehe
@claytonsilva

**Comment by claytonsilva** [comment]
@lucianopf segura que vou ver de meia noite as seis, segunda feira é dia lindo :D

**Comment by claytonsilva** [comment]
coloca assign pra mim @lucianopf

**Comment by lucianopf** [comment]
Bem que eu queria mas o GH não ta deixando =/

![screen shot 2018-06-11 at 3 49 54 pm](https://user-images.githubusercontent.com/8251208/41251044-245aadd8-6d8f-11e8-8c8f-47f0925dae8a.png)

**Comment by claytonsilva** [comment]
ahueaeahueahueahue pode deixar voce sendo culpado. to olhando aqui

**Comment by claytonsilva** [comment]
@CarolPC pra fechar o cerco e conseguir reproduzir legal aqui, qual a versão do angular-cli que está usando?

**Comment by CarolPC** [comment]
@claytonsilva estou usando a 6.0.2

**Comment by thiamsantos** [comment]
@CarolPC eu acho que o problema está acontecendo porque o angular está tentando importar a versão do cep-promise usado no node. 

Eu consegui resolver aqui importando diretamente o bundle para o browser:
```js
import * as cep from 'cep-promise/dist/cep-promise-browser.js';

cep('05010000')
  .then(console.log);
```

Você pode também fazer um [alias do cep-promise apontando para o bundle do browser](https://www.typescriptlang.org/docs/handbook/module-resolution.html#path-mapping). É só adicionar essa opção ao seu tsconfig.json dentro de `compilerOptions`. 
```json
{
  "compilerOptions": {
    "baseUrl": "./",
    "paths": {
      "cep-promise": ["node_modules/cep-promise/dist/cep-promise-browser.js"]
    }
  }
}
```
Eu testei em projeto novo gerado pelo angular-cli. O repositório pode ser encontrado [aqui](https://github.com/thiamsantos/angular-cep).

**Comment by claytonsilva** [comment]
indo direto pelo angular-cli dá realmente o resultado relatado e inclusive já levantaram a bola desse problema:

https://github.com/angular/angular-cli/issues/10698

ele já está aberto lá, a solução do @thiamsantos é a mais prudente por enquanto até eles resolverem

**Comment by CarolPC** [comment]
@thiamsantos @claytonsilva muito obrigada pela ajuda!
Importando diretamente o bundle para o browser funcionou!

**Comment by lucianopf** [comment]
Dado que isso infelizmente é um problema do Angular (TS ❤️ ) vou fechar a issue =D
