### ISSUE TITLE
Muitos erros no console.

### ISSUE THREAD

**Issue by klawdyo** [filipedeschamps/cep-promise#121]
Quando uma requisição retorna falha de algum dos serviços, o console fica cheio de erros.

![image](https://user-images.githubusercontent.com/100168/44961801-70568280-aeed-11e8-8b69-e2d2760bb6ed.png)

O catch tá pegando legal e só está sendo chamado quando todos estão com erro, conforme previsto. Só gostaria de deixar o console limpo, visto que não é muito profissional colocar em produção um produto cheio de erros aparecendo pro usuário. 

Poderia ter uma opção para desabilitar esses logs em produção?

**Comment by lucianopf** [comment]
Bom dia @klawdyo esse é um problema que eu venho tentando atacar por algum tempo mas não é tão trivial quanto parece =/

Existem algumas razões pro request dar erro, algumas delas eu consigo ver no seu console que parecem fáceis de consertar, por exemplo o uso do mesmo protocolo (https ou http) do que a origin.

Alguns não tanto, como por exemplo quando um dos serviços realmente retornam um erro, e portanto isso não mais é solucionável via lib mas sim na API do service que estamos usando. 

O problema é que usamos o fetch do browser (quando disponível) e o comportamento padrão dele é para alguns erros jogar no console de forma intratável, tenta por exemplo executar o seguinte código:

```
fetch('https://github.com/filipedeschamps/cep-promise/issues/121/404').then(console.log).catch(console.log)
```

Que resultado, MESMO tratando no catch é um `console.error` no navegador:
![screen shot 2018-09-03 at 9 48 57 am](https://user-images.githubusercontent.com/8251208/44987763-ac75fb80-af5e-11e8-85c6-6917aa531f4d.png)

Eu acho isso bizarro também, mas é o comportamento nativo do fetch já embarcado nos navegadores =S


De qualquer forma, continuo buscando soluções pra esse maldito `console.error` que também me incomoda HORRORES! 😂 👍 

(E aceito qualquer dica que tiver sobre o assunto!!! hehehe)

**Comment by lucianopf** [comment]
[Mais uma ref triste =/](https://stackoverflow.com/questions/41515732/hide-401-console-error-in-chrome-dev-tools-getting-401-on-fetch-call)

**Comment by brunooomelo** [comment]
fiz um teste simples com console.clear, acho que funcionou.

```js
fetch('https://github.com/filipedeschamps/cep-promise/issues/121/404')
  .then(console.clear)
  .catch(console.clear)
``` 

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/12174318/54562908-b3b6a100-49a6-11e9-9f13-1a896db410bb.gif)

**Comment by brunooomelo** [comment]
fiz outros testes aqui, e funcionou bem, o problema que aparece "Console was cleared".

**Comment by lucianopf** [comment]
O problema é que limpa o console, o que não necessariamente é o desejado por quem ta desenvolvendo =/

Mas muito obrigado por lembrar disso @brunooomelo !! 🤓 👏

**Comment by quinhone** [comment]
https://proxier.now.sh/http://www.cepaberto.com/api/v2/ceps.json?cep=78095390
some errors in console:
- Unauthorized
- Internal Server Error
- Forbidden

**Comment by quinhone** [comment]
warning:
blocked cross-origin response https://viacep.com.br

**Comment by lucianopf** [comment]
Hum, o do proxier me parece estar ligado com a requisição do `cepaberto` 🤔 
Vou dar uma olhadinha melhor =D

Misericórdia, o viacep começou a bloquear CORS agora, vou colocar ele no proxy então tbm 🤦‍♂

**Comment by lucianopf** [comment]
Cepaberto:
<img width="1045" alt="Screen Shot 2019-04-29 at 18 20 10" src="https://user-images.githubusercontent.com/8251208/56927816-7831eb00-6aab-11e9-8ac4-5cde53393fa7.png">

@filipedeschamps precisamos pensar melhor nesse service, talvez desliga-lo, o que acha? 🤔

**Comment by filipedeschamps** [comment]
Vish!! Eu topo total 👍

**Comment by lucianopf** [comment]
Muito obrigado @quinhone , abri um PR para desabilitar o serviço problemático e injetar o proxy que burla as regras de CORS pra prosseguirmos utilizando o service `ViaCep` que ao meu ver é o mais completinho de todos 😬

**Comment by quinhone** [comment]
> Cepaberto:
> <img alt="Screen Shot 2019-04-29 at 18 20 10" width="1045" src="https://user-images.githubusercontent.com/8251208/56927816-7831eb00-6aab-11e9-8ac4-5cde53393fa7.png">
> 
> @filipedeschamps precisamos pensar melhor nesse service, talvez desliga-lo, o que acha? 🤔

Apoio, ele está dando muito erro 500

**Comment by filipedeschamps** [comment]
Pessoal, o @lucianopf fez um fix que está na mais recente versão: `cep-promise@3.0.8`

![image](https://user-images.githubusercontent.com/4248081/70102074-e9122600-15eb-11ea-8f2f-6335b1f190ed.png)

**Comment by filipedeschamps** [comment]
Pessoal, estou fechando essa issue após o lançamento do `cep-promise@3.0.9` mas qualquer coisa sintam-se livres em reabrir ela caso o problema persista 👍
