### ISSUE TITLE
Erro ao buscar CEP - CORS

### ISSUE THREAD

**Issue by mathmarques** [filipedeschamps/cep-promise#126]
Olá! 
Estou tendo um problema com CORS ao importar o package e transpilar com Webpack para um bundle. Pois dessa forma, ao utiliza-lo no browser não está adicionando o PROXY para evitar isso.
Encontrei a Issue #98 e a solução dela falava de importar uma versão específica para browser porém ela não existe mais.
Existe alguma solução mais nova?

Versão 3.03

**Comment by lucianopf** [comment]
Boa noite @mathmarques tudo certinho?!
A gnt mudou um pouco a arquitetura do projeto e não temos mais a versão pra web em arquivos separados, no final de semana irei dar uma olhadinha nesse seu problema e tentar ver se acho uma solução secundária, mas no momento teria como vc fazer um teste por favor? 😬 

Vc ja tentou configurar o target do webpack pra web? 🤔 
[feature ref](https://webpack.js.org/concepts/targets/) e [targets available](https://webpack.js.org/configuration/target/)

**Comment by mathmarques** [comment]
Tudo ótimo @lucianopf ! E vc?
Não estou com ambiente de desenvolvimento do meu trabalho aqui no meu computador pessoal, na segunda feira testo e dou um retorno, ok?

Vlws!

**Comment by mathmarques** [comment]
@lucianopf 
Como fiquei de dar um feedback, mesmo com `target` para web o proxy não é adicionado =/

**Comment by lucianopf** [comment]
Show, brigadão por ter testado @mathmarques !! 

Vou dar um jeito nisso e te pingo dnv pra testar! ^^

(Enquanto isso se quiser usar uma versão mais antiga fica a vontade mano! ^^)

**Comment by mccraveiro** [comment]
@lucianopf podemos fechar essa issue? Já foi corrigida no PR #130 certo?

**Comment by filipedeschamps** [comment]
@mccraveiro você por aqui 😍

**Comment by lucianopf** [comment]
@mccraveiro sim, mas eu tava mantendo aberta pq na real isso gerou uma nova isso que eu ainda tenho que abrir, que é referente ao problema no processo de build que ele teve 😢 

Na real o problema ta resolvido na maioria dos casos, mas em alguns casos o  bundler não pega a versão pinada pra web e tenta resolver o módulo como se fosse do Node o que faz com que ele não funcione como o esperado 😢 

@filipedeschamps e @mccraveiro acham que isso é uma issue nova mesmo?

**Comment by ivmarcos** [comment]
Fala pessoal, estamos usando aqui com Webpack e Vue e também está estourando alguns erros relacionados a cors. 

![screenshot from 2019-01-16 17-43-57](https://user-images.githubusercontent.com/1471237/51274567-a6853200-19b6-11e9-8e9c-2c23a165e41c.png)

Tentei usar a solução de contorno #98 que pareceu relacionada mas também não tive sucesso.

**Comment by mathmarques** [comment]
@ivmarcos 
O Webpack faz um polyfill do process do Node para o browser.
Da uma olhada aqui: https://webpack.js.org/configuration/node/
E por isso a [checagem no codigo](https://github.com/filipedeschamps/cep-promise/blob/master/src/services/index.js#L11-L12) para utilização ou não do proxy não funciona no bundle gerado pelo Webpack.
Uma sugestão para você seria desativar esse polyfill:
```
module.exports = {
  //...
  node: {
    process: false,
  }
};
```
Obs: não testei ainda e não sei quais outras libs isso pode atrapalhar.

Inclusive, esse polyfill por padrão deverá ser [retirado na próxima versão do Webpack](https://github.com/webpack/changelog-v5/blob/master/README.md#automatic-nodejs-polyfills-removed)

**Comment by lucianopf** [comment]
@ivmarcos isso ainda é algo que to analisando se foi um bom movimento, mas claramente o erro ta do lado dos bundlers de considerar `process` onde na verdade não deveria existir, já que estamos no contexto do browser =S

Talvez eu volte atrás e busque outra maneira de deixar ele isomórfico, vou estudar as opções e mantenho vcs atualizados! 😬 

Enquanto isso acho que a solução do querido @mathmarques deve resolver, consegue testar por favor? 🙏

**Comment by ivmarcos** [comment]
@mathmarques, @lucianopf, obrigado e desculpe a demora! Realmente desativando o node no webpack resolve o problema relacionado ao uso do proxy/cors, mas entendo que isso pode invialibizar o uso do process em alguns projetos que dele dependem, como em casos que usam ```process.env[variavel_de_ambiente]```. Fiz um PR #137 sugerindo pequenas mudanças, como usar window ao invés de process para identificar se é o navegador.

**Comment by ivmarcos** [comment]
@mathmarques para mim o problema do cors foi resolvido com a release da [v3.0.6](https://github.com/filipedeschamps/cep-promise/releases/tag/v3.0.6).

**Comment by lucianopf** [comment]
Ótimo, irei fechar essa issue! 😬
