### ISSUE TITLE
Novo contribuidor ficou massa no readme kkkkkk

### ISSUE THREAD

**Issue by filipedeschamps** [filipedeschamps/cep-promise#133]
@otaviopace olha como apareceu o readme aqui kkkkkk

<img width="938" alt="image" src="https://user-images.githubusercontent.com/4248081/49815534-1fa7be80-fd53-11e8-80e3-8e784a420c84.png">

**Comment by lucianopf** [comment]
![screen shot 2018-12-11 at 15 47 40](https://user-images.githubusercontent.com/8251208/49819259-1b33d380-fd5c-11e8-8232-a63de04debda.png)

😂

**Comment by otaviopace** [comment]
kkkkkkkkkkkkkkk, o plano malígno do criador do [cep-callback](https://github.com/otaviopace/cep-callback) finalmente virou realidade

**Comment by filipedeschamps** [comment]
HAHAHAHAHAHA
