### ISSUE TITLE
CepPromiseError: CepAbertoService is not a function

### ISSUE THREAD

**Issue by FelipeValencio** [filipedeschamps/cep-promise#138]
at throwApplicationError (C:\Users\felip\Downloads\cep-promise-master\src\cep-promise.js:84:9)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
    at Function.Module.runMain (module.js:696:11)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3
  name: 'CepPromiseError',
  message: 'CepAbertoService is not a function',
  type: undefined,
  errors: undefined }
undefined

Sou muito leigo em Nodejs, java e etc tentei de tudo e procurei em tudo que é lugar não achei solução.

**Comment by lucianopf** [comment]
Boa noite @FelipeValencio, tudo certo amigo?

Pelo que entendi vc baixou o repositório e está tentando executar o arquivo da pasta src, correto?

Para utilizar dessa forma acredito que vc deve apontar para o arquivo da pasta dist, mas de qualquer forma essa não é a forma mais recomendada de utilizar a biblíoteca 😢 

Há um guia simples de utilização [aqui](https://github.com/filipedeschamps/cep-promise#instala%C3%A7%C3%A3o) e se mesmo assim vc não obter êxito pode mandar msg que a gnt tenta te ajudar e te encaminhar para os guias de como integrar a lib! 😬 🤓

**Comment by FelipeValencio** [comment]
Bom dia Filipe obrigado pela resposta vou ler novamente o guia e ver se consigo rodar dessa forma

Obter o Outlook para Android<https://aka.ms/ghei36>

________________________________

**Comment by FelipeValencio** [comment]
Boa tarde Filipe, só consegui mexer com o código novamente hoje, segui o que estava na documentação e consegui fazer rodar, obrigado e parabéns pelo código!

________________________________
De: Luciano Pellacani Franca <notifications@github.com>
Enviado: quarta-feira, 20 de fevereiro de 2019 22:59
Para: filipedeschamps/cep-promise
Cc: FelipeValencio; Mention
Assunto: Re: [filipedeschamps/cep-promise] CepPromiseError: CepAbertoService is not a function (#138)


Boa noite @FelipeValencio<https://github.com/FelipeValencio>, tudo certo amigo?

Pelo que entendi vc baixou o repositório e está tentando executar o arquivo da pasta src, correto?

Para utilizar dessa forma acredito que vc deve apontar para o arquivo da pasta dist, mas de qualquer forma essa não é a forma mais recomendada de utilizar a biblíoteca 😢

Há um guia simples de utilização aqui<https://github.com/filipedeschamps/cep-promise#instala%C3%A7%C3%A3o> e se mesmo assim vc não obter êxito pode mandar msg que a gnt tenta te ajudar e te encaminhar para os guias de como integrar a lib! 😬 🤓

**Comment by lucianopf** [comment]
@filipedeschamps  ❤️

**Comment by filipedeschamps** [comment]
Vocês são demais!!! 👍
