### ISSUE TITLE
[Off-Topic] CEP Promise PHP

### ISSUE THREAD

**Issue by claudsonm** [filipedeschamps/cep-promise#142]
Projeto incrível!

Estávamos precisando de um pacote que fizesse as requisições concorrentemente em nosso backend em PHP, porém não encontramos nada satisfatório. Tomei a liberdade de criar um pacote para PHP inspirado no CEP Promise. A única coisa que ainda não consegui reproduzir foram os mocks das requisições para efetuar os testes de unidade. No mais, preciso dar uma melhorada no README adicionando as instruções de uso.

A quem interessar, aqui está o link do projeto: [claudsonm/cep-promise-php](https://github.com/claudsonm/cep-promise-php).

**Comment by lucianopf** [comment]
Caraca mano, animal!!! 👏 👏 👏 👏

**Comment by filipedeschamps** [comment]
Que massa!!! Parabéns meu caro :)

**Comment by filipedeschamps** [comment]
Vou fechar essa issue, e fique de olho num serviço de cep que queremos levantar para adicionar como um dos seus providers 🤝
