### ISSUE TITLE
Erro ao inicializar

### ISSUE THREAD

**Issue by SistemasSouza** [filipedeschamps/cep-promise#143]
Ao tentar utilizar a lib com React tenho o seguinte erro .

![image](https://user-images.githubusercontent.com/13488005/56688193-7385c500-66ae-11e9-8ece-1bed4fffa7f0.png)

meu código e o seguinte 

import cepPromise from 'cep-promise'

cepPromise(value).then(res => console.log(res))

**Comment by SistemasSouza** [comment]
identifiquei o problema, favor desconsiderar a issue

**Comment by lucianopf** [comment]
Que massa que tu conseguiu achar o erro @SistemasSouza !! 👏 🚀 

Se tiver disposto a compartilhar eu tenho certeza que será útil para alguém no futuro ao buscar pela resolução de um erro similar 😬

**Comment by SistemasSouza** [comment]
Bem, o meu problema ocorreu devido a uma desatenção, eu estava passando o **event** completo como parâmetro para a função cep, ao invés do valor apenas. Corrigido isso tudo funcionou normal.

**Comment by lucianopf** [comment]
Boa manow!! 👏 

Dicazinha besta, pra evitar ficar chamando a lib pra cada tecla que o user apertar vc pode validar se o tamanho da string de input do user tem `.length >= 8`, daí vc diminui o consumo de banda pelo lado do cliente 😬

**Comment by SistemasSouza** [comment]
No meu caso, estou chamando a lib com onBlur do react, ai a lib só e invocada quando o campo perde o focus. Mesmo assim sua dica e muito válida, vou implementar . vlws ✌✌
