### ISSUE TITLE
Erro de CORS

### ISSUE THREAD

**Issue by quinhone** [filipedeschamps/cep-promise#145]
POST https://proxier.now.sh/https://apps.correios.com.br/SigepMasterJPA/AtendeClienteService/AtendeCliente net::ERR_ABORTED 502
add:1 Access to fetch at 'https://proxier.now.sh/https://apps.correios.com.br/SigepMasterJPA/AtendeClienteService/AtendeCliente' from origin 'http://localhost:8080' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

**Comment by lucianopf** [comment]
Huummm, interessante esse daí! 🤔 

Eu acabei de testar o proxier e ta funcionando direitinho, consegue pfv me confirmar se isso está acontecendo constantemente? 

😬

**Comment by welderlourenco** [comment]
Olá, boa noite @lucianopf @quinhone ... infelizmente, o mesmo problema acontece comigo também... isso não acontecia antes... agora, as vezes o request demora 1 minuto para completar, as vezes dá erro apenas com viacep, as vezes da erro com viacep e correios... muito estranho... o que será que está acontecendo?
![Screenshot from 2019-10-08 23-38-45](https://user-images.githubusercontent.com/5265316/66447651-573fcf80-ea25-11e9-9bda-d66dbf3ff77b.png)
![Screenshot from 2019-10-08 23-41-09](https://user-images.githubusercontent.com/5265316/66447652-573fcf80-ea25-11e9-97fe-0516ee4553bf.png)

**Comment by welderlourenco** [comment]
Boa noite @lucianopf @quinhone. Infelizmente, o mesmo problema acontece aqui...

Um tanto imprevisivel... algumas vezes o request demora mais de 30s para concluír (e as vezes concluí com erro)... o erro acontece todas as vezes com o ViaCEP, e, algumas vezes, com os Correios também (o que impede de se obter os dados do cep)... isso não acontecia antes. Que será?

> Access to fetch at 'https://proxier.now.sh/https://viacep.com.br/ws/14948438/json/' from origin 'http://meusite.com.br' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
cep.js:10 GET https://proxier.now.sh/https://viacep.com.br/ws/14948438/json/ net::ERR_FAILED

> Access to fetch at 'https://proxier.now.sh/https://viacep.com.br/ws/14948438/json/' from origin 'http://meusite.com.br' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
cep.js:10 GET https://proxier.now.sh/https://viacep.com.br/ws/14948438/json/ net::ERR_FAILED
Access to fetch at 'https://proxier.now.sh/https://apps.correios.com.br/SigepMasterJPA/AtendeClienteService/AtendeCliente' from origin 'http://meusite.com.br' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
cep.js:10 POST https://proxier.now.sh/https://apps.correios.com.br/SigepMasterJPA/AtendeClienteService/AtendeCliente net::ERR_FAILED

**Comment by lucianopf** [comment]
Gente, isso é muito estranho, ou o proxier ta com algum container não saudável ou o processo de build de vcs pode estar alterando algo 🤔 

Veja só, um exemplo no site da Pagar.me que não tem nada de especial com o `cep-promise`

<img width="1002" alt="Screen Shot 2019-10-10 at 20 15 56" src="https://user-images.githubusercontent.com/8251208/66613166-ed493680-eb9a-11e9-9831-82d3f0d676d8.png">

A demora realmente acontece principalmente por conta da instabilidade dos nossos provedores (até por isso temos 2 integrados hehehe) 😢 

Qual a stack e processo de build que tão usando? 😬

**Comment by rodrigomedeirosbrazil** [comment]
também tive problema aqui, coloquei a lib para buscar ceps em um sistema em reactjs, e está dando erro de cors. Porém fiz o teste no npm runkit e estava funcionando no mesmo cep.

**Comment by murilosandiego** [comment]
Mesmo problema aqui @rodrigomedeirosbrazil

**Comment by murilosandiego** [comment]
Aparentemente parece ser um erro no proxy.

![image](https://user-images.githubusercontent.com/11686438/67431721-43ff3900-f5bb-11e9-9eb5-265cd4f38e01.png)

![image](https://user-images.githubusercontent.com/11686438/67431848-81fc5d00-f5bb-11e9-8ae9-c050db9d4f45.png)

**Comment by lucianopf** [comment]
Boa noite galera, desculpa a demora, tava viajando =/

Aparentemente é algum problema com a infraestrutura que o "proxier" ta hospedado, dei uma re-configurada nele e deve voltar ao normal, se isso continuar acontecendo vou ter que deployar o serviço na mão mesmo pra evitar esses problema de auto-scale de versão antiga do Now =/

**Comment by marceloivanofre** [comment]
Estou com o mesmo erro em uma aplicação local, porém no npm run kit funciona normalmente.

**Comment by lucianopf** [comment]
> Estou com o mesmo erro em uma aplicação local, porém no npm run kit funciona normalmente.

O mesmo erro de CORS ou o 502 citado acima @marceloivanofre ?

**Comment by marceloivanofre** [comment]
O de CORS, mas parece ser pontual, em algumas requisições ele dá o erro e em outras não.

**Comment by Davigl** [comment]
também to recebendo o mesmo erro de CORS em algumas requisições.

**Comment by lucianopf** [comment]
Gente, isso é muito estranho, ainda não to conseguindo pensar numa possível causa 🤔 

O erro de CORS não é intermitente, se não é permitido sempre deve acusar o erro, se ao menos uma vez passou com sucesso não deve eventualmente ter problemas (já que é o mesmo servidor sendo usado)


Uma dúvida que estou é em qual versão do módulo vcs estão tendo problemas?

Se não me engano no passado não usavamos o proxy (que resolve o problema do CORS) em todos os providers, sendo essa uma possível causa de eventualmente um serviço demorar pra responder e o fallback (sem o proxy pq ta com a versão antiga) assume, e esse por sua vez teve as regras atualizadas no servidor para o bloquei de requisições de fora de domínios permitidos 🤔

**Comment by valdinei** [comment]
![Screen Shot 2019-11-27 at 17 53 18](https://user-images.githubusercontent.com/1458766/69758636-ce006b80-113e-11ea-8bac-085647a39487.png)

**Comment by dmvvilela** [comment]
Estou tendo o mesmo problema, mas só de vez em quando. Estou usando reactjs

**Comment by lucianopf** [comment]
Galera, vamos quebrar o problema em 2 issues distintas?

Aparentemente vc está tendo problemas 502 e não o CORS.

Acho que fica mais fácil de identificar os problemas se a gnt quebrar eles, o que acham?

**Comment by Herbert2122** [comment]
Bom dia estou tendo o mesmo problema, no meu caso nenhuma requisição dá certo , 

![image](https://user-images.githubusercontent.com/29212058/69815182-8fb58b80-11d4-11ea-91ba-e1c959067629.png)

@lucianopf   no console log ele retorna esse erro de CORS e no proxier ele da 502 de bad gateway

![image](https://user-images.githubusercontent.com/29212058/69815316-cc818280-11d4-11ea-8ab9-bcb1bf1fdb50.png)

**Comment by Herbert2122** [comment]
Se ajudar em algo eu encontrei esse artigo 
https://medium.com/@dtkatz/3-ways-to-fix-the-cors-error-and-how-access-control-allow-origin-works-d97d55946d9
que menciona uma extensão para o navegador, eu instalei e realmente o erro de CORS não aparece mais no console log, mas o erro 502 continua aparecendo.
O Cep está correto pois funciona via teste no runkit
![image](https://user-images.githubusercontent.com/29212058/69815719-af00e880-11d5-11ea-911b-f3fb6b6c3b0b.png)

**Comment by Herbert2122** [comment]
Alguém já tem alguma dica sobre isso?

**Comment by lucianopf** [comment]
@Herbert2122 estamos lidando com isso em outra issue, mas já de antemão, encontramos o problema e estamos tratando =/

https://github.com/filipedeschamps/cep-promise/issues/149#issuecomment-559970519

**Comment by Herbert2122** [comment]
Obrigado

**Comment by Herbert2122** [comment]
Obrigado @lucianopf  tem alguma dica? estou com uma outra api que estou usando que está dando esse mesmo problema, mas lá não tem suporte, então vou ter que resolver por aqui mesmo.

**Comment by lucianopf** [comment]
Há a possibilidade de resolver os ceps do lado do seu servidor? Se tiver já evita esses probleminhas que estamos tendo 😢

**Comment by Herbert2122** [comment]
Estou procurando alguma forma , até o momento não consegui, parece que a ideia é usar um proxy mas não consigo implementar na stack que estou usando (ReactJS), a outra api que mencionei é para um outro serviço, com ela acontece o mesmo erro de cors :(

**Comment by lucianopf** [comment]
@Herbert2122 mestre, pra poder te liberar fiz já um "mini-deploy" que consegue te ajudar a resolver os ceps usando apenas o serviço do Viacep =/

Hoje a noite pretendo trabalhar mais nisso e tentar fazer ele ficar 100% no cep-promise dnv!

Pra usar basta usar a url `https://proxier.now.sh/api?url=https://viacep.com.br/ws/<SEU_CEP_AQUI>/json`

Exemplo:

```js
fetch('https://proxier.now.sh/api?url=https://viacep.com.br/ws/04180112/json')
  .then(v => v.json())
  .then(console.log).catch(console.log)
```

Essa é uma solução paleativa, então continua de olho aqui nessa issue do github pfv pra novidades! 😬

**Comment by Herbert2122** [comment]
Maravilha muito obrigado

**Comment by filipedeschamps** [comment]
Pessoal, o @lucianopf fez um fix que está na mais recente versão: `cep-promise@3.0.8`

![image](https://user-images.githubusercontent.com/4248081/70102074-e9122600-15eb-11ea-8f2f-6335b1f190ed.png)

**Comment by Herbert2122** [comment]
Pessoal olha que coisa doida dentro do react eu continuo recebendo o mesmo erro:

![image](https://user-images.githubusercontent.com/29212058/70140106-beb77b80-1672-11ea-8e05-056a2a17fa8f.png)

porém via browser ele funciona bem 
![image](https://user-images.githubusercontent.com/29212058/70140145-d55dd280-1672-11ea-9b0c-0fa9f52513e9.png)

Será que algo nessa stack vai impedir o uso ?

**Comment by Herbert2122** [comment]
@lucianopf  é show mesmo, essa comunidade é muito massa,
obrigado por isso
cep-promise é show que implementação simples ! =) =D

**Comment by Herbert2122** [comment]
@lucianopf eu continuo tendo alguns problemas, minha stack é o react , você acha que isso pode estar influenciando?
Tem momentos que funciona bem e tem momentos que acontece isso

![image](https://user-images.githubusercontent.com/29212058/70141838-a34e6f80-1676-11ea-9fce-a0998fdadba7.png)

**Comment by valdinei** [comment]
@lucianopf também continuo com o problema anterior, a consulta retornando 308
![Screen Shot 2019-12-04 at 09 26 45](https://user-images.githubusercontent.com/1458766/70142570-4eabf400-1678-11ea-8a67-f88d81b5ac9d.png)

**"cep-promise": "^3.0.8"**

**Comment by lucianopf** [comment]
@Herbert2122 não estou conseguindo reproduzir o erro 😢 

Vou continuar investigando!

@valdinei aparentemente vc não atualizou a sua lib, a request deveria ser para `/api?url=...`, consegue confirmar pfv se está na versão mais atual possível no browser? (pode estar no cache do browser)

**Comment by valdinei** [comment]
@lucianopf fato, eu tenho dois projetos, eu atualizei um e testei no outro. Atualizado e funcionando!  **Obrigado pelo empenho!**

**Comment by lucianopf** [comment]
Achei a causa @Herbert2122  🙌 

![Screen Shot 2019-12-04 at 09 59 13](https://user-images.githubusercontent.com/8251208/70144466-c2e89680-167c-11ea-820c-d075f3fb8547.png)

O problema está nos serviços que usamos para buscar o CEP, aparentemente eles não estão aguentando também a quantidade de requisições que estamos fazendo =/

Especialmente o ViaCep pelo que vi aqui =/

Com a sugestão do @filipedeschamps pra usar uma base de cache iremos conseguir evitar um pouco esse problema, mas provavelmente teremos que encontrar outros provedores de CEP para incluir na lib =/

**Comment by Herbert2122** [comment]
@lucianopf  entendi, faz sentido , acredito que o conceito foi o mesmo usado na https://api.pagar.me/1/zipcodes/ correto? fazendo uns testes com ela, está respondendo bem

**Comment by lucianopf** [comment]
Exatamente, usamos uma espécie de cache pra poder ajudar na resolução dos ceps =/

**Comment by Herbert2122** [comment]
Ok vamos esperar obrigado pelo empenho e apoio !

**Comment by kvnol** [comment]
![image](https://user-images.githubusercontent.com/3299130/70348216-00961c80-1841-11ea-9eb7-b38589a2a6dd.png)

caiu de novo, né? :(

**Comment by lucianopf** [comment]
@kvnol na verdade não, ta funcionando direitinho aqui quando testei, será que não era o provedor que tava tendo problemas? 🤔

**Comment by victorjatoba** [comment]
Atualizei e funcionou! Parabéns @lucianopf 

usando:
"react": "^16.8.1",

**Comment by gabrieljob** [comment]
Boa tarde, estava utilizando o seguinte erro:
![Capturar](https://user-images.githubusercontent.com/45143271/71730787-dc1e6780-2e21-11ea-9d4e-80fb2bbc68f9.PNG)

**Comment by lucianopf** [comment]
Aparentemente isso é culpa da instabilidade do provider =/
Isso está acontecendo com qual frequência? 

https://proxier.now.sh/api?url=https://viacep.com.br/ws/93220220/json

<img width="1229" alt="Screen Shot 2020-01-03 at 16 10 39" src="https://user-images.githubusercontent.com/8251208/71743594-b1450b00-2e43-11ea-8d1d-73e885d179f9.png">

**Comment by gabrieljob** [comment]
Praticamente todo o tempo, quando vou efetuar um registro para consultar o CEP, ele informa este erro :/

**Comment by filipedeschamps** [comment]
Pessoal, o @lucianopf acabou de publicar a versão `cep-promise@3.0.9` que remove o Proxier do Viacep e todas essas chamadas irão funcionar normalmente, via browser ou server. Vou fechar a issue por enquanto mas qualquer problema, só reabrir 👍

**Comment by marinastavares** [comment]
ainda com o mesmo problema :/

**Comment by marinastavares** [comment]
to recebendo esse erro ainda :/

**Comment by samirissa00** [comment]
Ola , alguma coisa mudou :? Estava usando até pouco tempo no dev local sem problemas , mas agora dá erro >>

> localhost:8080/#/pensionistas/detalhe_pensionista/090d6653-9a71-43f4-b1e9-1cf2f2b7739c/enderecos_pensionista:1 Access to XMLHttpRequest at 'https://viacep.com.br/ws/04736-001/json' from origin 'http://localhost:8080' has been blocked by CORS policy: Request header field authorization is not allowed by Access-Control-Allow-Headers in preflight response.

**Comment by lucianopf** [comment]
Meu pai amado... :cry: 

@filipedeschamps vou mudar a abordagem e usar o BrasilAPI no front, o que acha? :eyes: 
(É um inception maroto mas acho que faz sentido)

**Comment by giovanigenerali** [comment]
Eu já uso a api do ```viaCEP``` mas queria usar a ```cep-promise``` por ter uma segunda chamada nos correios só está com erro.
![Screen Shot 2020-07-31 at 14 36 48](https://user-images.githubusercontent.com/41435/89061653-79e7ff80-d33b-11ea-95e1-a89d486e7000.png)

Testei usando a ```BrasilAPI``` que usa o ```cep-promise``` e por hora está de boa 👍
![Screen Shot 2020-07-31 at 14 50 08](https://user-images.githubusercontent.com/41435/89062606-24145700-d33d-11ea-8abc-ddd2d233e359.png)
