### ISSUE TITLE
Failed to load resource: Request header field Content-Type is not allowed by Access-Control-Allow-Headers.

### ISSUE THREAD

**Issue by nncl** [filipedeschamps/cep-promise#154]
Olá, primeiramente gostaria de parabenizá-los, o cep-promise facilita bastante a vida rs.

Recentemente percebi que no iOS 12.4, é retornado o seguinte erro:

![Screen Shot 2020-01-16 at 14 28 16](https://user-images.githubusercontent.com/6740387/72548225-08e46d00-386d-11ea-9daf-1941770f5fff.png)
![Screen Shot 2020-01-16 at 14 28 51](https://user-images.githubusercontent.com/6740387/72548226-097d0380-386d-11ea-8fbf-7ea9a8bb1433.png)
![Screen Shot 2020-01-16 at 14 28 56](https://user-images.githubusercontent.com/6740387/72548228-097d0380-386d-11ea-9d1e-08d380f4d8ab.png)
![Screen Shot 2020-01-16 at 14 29 01](https://user-images.githubusercontent.com/6740387/72548229-097d0380-386d-11ea-89ef-356464eb539a.png)

Os testes foram feitos pelo simulador e pelo device em um iPhone 6.

Poderia me ajudar? Desde já agradeço :)

**Comment by filipedeschamps** [comment]
@nncl por favor, você poderia testar na versão `cep-promise@3.0.9`? 👍

**Comment by nncl** [comment]
Olá @filipedeschamps. Realizei um novo teste e o resultado de sucesso é retornado pelo viacep :) Porém, uma das requisições - aparentemente correios - o problema persiste.

![Screen Shot 2020-02-03 at 16 54 55](https://user-images.githubusercontent.com/6740387/73686090-1c356c00-46a6-11ea-8303-9d18c527fdbc.png)

![Screen Shot 2020-02-03 at 16 55 23](https://user-images.githubusercontent.com/6740387/73686169-3c652b00-46a6-11ea-8bf5-2d953465d5c8.png)

![Screen Shot 2020-02-03 at 16 55 30](https://user-images.githubusercontent.com/6740387/73686177-3ff8b200-46a6-11ea-9841-7cebdcb1995f.png)

De qualquer forma, o viacep retorna corretamente :)

Obrigado pelo retorno 👍

**Comment by filipedeschamps** [comment]
Show! Esse é o comportamento esperado 🤝 Dado que ele tenta os dois em paralelo, o dos correios vai dar problema, mas com a garantia de que o Viacep vai funcionar 👍 e eu e o @lucianopf estamos trabalhando num terceiro provider com um monte de melhorias, dai o negócio vai ficar massa!
