### ISSUE TITLE
Erro de cors em todas as  chamadas

### ISSUE THREAD

**Issue by quinhone** [filipedeschamps/cep-promise#155]
Todas as chamadas estão dando erro de cors
![Capturar](https://user-images.githubusercontent.com/3433668/73401349-5c20db80-42c1-11ea-8f79-257fcc80565d.JPG)

**Comment by filipedeschamps** [comment]
Obriagado pela issue @quinhone !

@lucianopf será que vale lançar uma versão sem o proxier para pegar pelo viacep direto?

**Comment by lucianopf** [comment]
O problema é que se não me engano o ViaCep tbm ta com CORS ativo agora =/

Vou dar uma olhadinha!

**Comment by lucianopf** [comment]
Pior que não, ta liberado!!
To abrindo PR aqui!

**Comment by lucianopf** [comment]
Boa, vlw pelo toque @quinhone !!

Vamos aos pontos @filipedeschamps e @quinhone :

O erro que vc está tendo @quinhone pode ser resolvido atualizando a versão da lib, a que vc ta usando usa uma versão antiga do serviço de proxy.

[link de como deveria estar o link](https://github.com/filipedeschamps/cep-promise/blob/master/src/utils/consts.js#L1)

Sobre lançar sem o proxier pro viacep faz sentido sim, no passado eles tinham bloqueado o cors mas agora acho que ta 100% liberado, vou criar um PR pra isso! ❤️

**Comment by filipedeschamps** [comment]
@quinhone por favor utilize a versão `cep-promise@3.0.9` com a alteração do @lucianopf que vai funcionar 👍
