### ISSUE TITLE
Adicionar ao README.md comando de instalação pelo Yarn

### ISSUE THREAD

**Issue by lokinmodar** [filipedeschamps/cep-promise#157]
Olá!

Acho a lib sensacional! Vocês poderiam colocar o comando para instalação via Yarn no README.md. :)

**Comment by filipedeschamps** [comment]
Show @lokinmodar ! Desafio para você: mandar um PR de como você acredita que ficaria legal o README com essa informação 👍

**Comment by filipedeschamps** [comment]
@lokinmodar fez o PR https://github.com/filipedeschamps/cep-promise/pull/158 e está `merged`!

Parabéns eu caro 👍
