### ISSUE TITLE
Atualizar o README.md

### ISSUE THREAD

**Issue by ftonato** [filipedeschamps/cep-promise#16]
Como sabemos, a documentação de um projeto é uma das partes mais importantes, então segue um modelo básico (**incompleto**) de um arquivo _README.md_ para descrever o projeto :)

---------------
# cep-promise

[![Coverage Status](https://coveralls.io/repos/github/filipedeschamps/cep-promise/badge.svg?branch=master)](https://coveralls.io/github/filipedeschamps/cep-promise?branch=master)

 Busca por CEP integrado ao banco de dados dos Correios - Node.js e Browser 

## Installation

```sh
# via npm
$ npm install cep-promise

# via github
$ git clone https://github.com/filipedeschamps/cep-promise.git
```

### Setup

```sh
$ cd cep-promise
$ npm install
```

## Contributing

1. Fork it ( https://github.com/filipedeschamps/cep-promise/fork )
2. Create your feature branch (`git checkout -b my-new-feature`)
3. Commit your changes (`git commit -am 'Add some feature'`)
4. Push to the branch (`git push origin my-new-feature`)
5. Create a new Pull Request

---------------

Acredito que seria legal adicionar também o tipo de licença e um gif de exemplo (de uso) no terminal o/

O que você acha @filipedeschamps?

**Comment by filipedeschamps** [comment]
@ftonato perfeito meu caro! Achei top, gostei do modelo Installation, Usage e Contributing. Se puder mandar PR seria show :+1:

**Comment by filipedeschamps** [comment]
Um detalhe importante é sobre o padrão nas mensagens de commit :) uso da mesma forma que o Anguar faz: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#commit

Claro, não tem tanto volume como o deles, mas é o mesmo princípio :)

**Comment by ftonato** [comment]
Segue o PR @filipedeschamps =)
