### ISSUE TITLE
Possibilitar escolher a api

### ISSUE THREAD

**Issue by luciancaetano** [filipedeschamps/cep-promise#164]
Permitir escolher a api a ser consumida e se usar ou não proxy.

**Comment by lucianopf** [comment]
Bom dia @luciancaetano , tudo certo?

Estamos discutindo isso na issue https://github.com/filipedeschamps/cep-promise/issues/163, vou fechar essa por se tratar de um assunto já em discussão, mas pfv, comenta lá na issue e participa da discussão tbm! 😬
