### ISSUE TITLE
Retornando "Todos os serviços de CEP retornaram erro."

### ISSUE THREAD

**Issue by ajfiumanee** [filipedeschamps/cep-promise#165]
Ao consultar um CEP que não consta na base está retornando sempre este erro.
Ex.: CEP: 15830-100 -> Era para retornar CEP não encontrado.

**Comment by lucianopf** [comment]
Boa tarde, tudo certinho?!

Pelo que consta no viacep.com.br e no site http://www.buscacep.correios.com.br esse CEP realmente não existe ou ainda não foi atualizado na base de dados oficial dos Correios, esse é um CEP novo? 🤔 

![Screen Shot 2020-03-13 at 18 05 55](https://user-images.githubusercontent.com/8251208/76659472-4c014a80-6555-11ea-88a8-c0eba7598a31.png)

**Comment by ajfiumanee** [comment]
Boa noite @lucianopf!
Este CEP nao existe, porem era p/ retornar "CEP nao encontrado na base" ou algo do tipo.
Que no casa está retornando erro, dei uma debugada +/- e vi que no return do Correrios tenta fazer replace em '/return' e não consta essa tag quando não à CEP.

![git](https://user-images.githubusercontent.com/34136203/76662333-6c80d300-655c-11ea-8616-c8a6e7b1f907.png)

**Comment by kaioduarte** [comment]
Caí de paraquedas aqui e dei uma rápida olhada no código 😅

@ajfiumanee não dá para fazer distinção se todos os serviços não encontraram de fato o CEP por causa do ViaCEP, pois ele apenas retorna ```{ erro: true }``` pra qualquer requisição inválida (CEP inexistente ou inválido).

**Comment by brunoflegler** [comment]
@ajfiumanee esse formato de `cep` está correto?, ele possue 1 número a mais. Ex:

```
const cep = require('cep-promise')
cep('150830-100').catch(console.log)

// { 
//   name: 'CepPromiseError',
//   message: 'CEP deve conter exatamente 8 caracteres.',
//   type: 'validation_error',
//   errors:
//  [ { message: 'CEP informado possui mais do que 8 caracteres.',
//      service: 'cep_validation' } ] 
// }
```

**Comment by ajfiumanee** [comment]
@brunoflegler me reparado, na hora digitei errado, o cep é 15830-100.

**Comment by ajfiumanee** [comment]
@brunoflegler não era p/ retornar cep nao encontrado?
![image](https://user-images.githubusercontent.com/34136203/81026154-88fc0600-8e4f-11ea-924d-3af58f0ce15d.png)

**Comment by brunoflegler** [comment]
@ajfiumanee o que acontece é que você não ta capturando o `catch` proposto pela implementação, como seu codigo não tem try/catch ele `explode` no seu console. Testa da seguinte forma:

```
const cep = require('cep-promise')

cep('15830-100')
  .then(response => console.log('Sucesso:', response))
  .catch(error => console.log(error.message))
```

**Comment by ajfiumanee** [comment]
Entendi @brunoflegler foi um erro de não me atentar no tratamento. obg!
