### ISSUE TITLE
CEP alterado

### ISSUE THREAD

**Issue by diegorodrigo90** [filipedeschamps/cep-promise#166]
![erro-correios-cep-alterado](https://user-images.githubusercontent.com/6834553/78371790-cfcfb500-759e-11ea-9a1d-bbf62a506beb.png)

CEP alterado retorna como não encontrado, é possível retornar o cep atualizado?

**Comment by lucianopf** [comment]
Infelizmente nós apenas consumimos a API dos provedores 😢
Mas de fato o CEP não existe mais, correto?

**Comment by diegorodrigo90** [comment]
> Infelizmente nós apenas consumimos a API dos provedores 
> Mas de fato o CEP não existe mais, correto?

Sim, mas eu precisaria de uma API que retomasse qual o novo CEP, ou que pelo menos ele foi alterado, vou continuar pesquisando. Obrigado!
