### ISSUE TITLE
alguém tomando timeout? 

### ISSUE THREAD

**Issue by fcavalcantirj** [filipedeschamps/cep-promise#173]
connect ETIMEDOUT 201.48.198.97:8083

**Comment by lucianopf** [comment]
Opa, bom dia mestre, tudo certo?

Testando aqui tudo parece normal, consegue pfv nos dar um pouco mais de contexto? :pray:

**Comment by fcavalcantirj** [comment]
Cara...re-testei aqui e foi... acho q eh a API dos correios q de vez em qd capota mesmo..... vcs sentem isso ou ela responde 100% das vezes sempre?

**Comment by fcavalcantirj** [comment]
bom, posso enviar trecho de código, mas pra mim ela parece bastante intermitente...mas tem cara de ser na API final...o IP que da timeout eh dos correios.

**Comment by fcavalcantirj** [comment]
Galera, era código meu....resolvi me inspirando nessa issue aqui

https://github.com/tc39/ecmascript-asyncawait/issues/72

**Comment by lucianopf** [comment]
De fato o serviço do Correios é bem intermitente, até por isso que usamos 3 serviços distintos :joy: 

Boa, que bom que deu certo mestre!

**Comment by fcavalcantirj** [comment]
Mas não sei pq, mesmo com Promise.All... tenho tomado mto..

Error: connect ETIMEDOUT 201.48.199.53:8083

código tá simples, segue um print...aceito sugestões...
![Screen Shot 2020-06-29 at 21 26 14](https://user-images.githubusercontent.com/7119341/86069030-25f1ae80-ba4f-11ea-807b-30f03dc3059a.png)

**Comment by fcavalcantirj** [comment]
mesmo código, mesmas condições, as vezes funciona as vezes não... =/ sensação que dá.

**Comment by fcavalcantirj** [comment]
Caros, foi mal... mas usei um codigo de testes, fora da aplicação, fiquei fazendo N testes...descobri oq era....ps... pra quem tiver problemas, a variavel tem q ser String rs. (preço). E tb nao pode ser acima de 3K.

**Comment by lucianopf** [comment]
Mestre, tenho a impressão que estamos falando de sistemas diferentes hehehe

O `cep-promise` resolve ceps e retorna o endereço do CEP, essa API que vc está usando aparentemente é a de cálculode frete do Correios :thinking:
