### ISSUE TITLE
Não funciona no "target = node" no ParcelJS

### ISSUE THREAD

**Issue by Rechdan** [filipedeschamps/cep-promise#176]
Quanto o Parcel vai compilar para rodar em um ambiente NodeJS ele tenta importar o arquivo `dist/cep-promise-browser.min.js`, fazendo com que ocorra o erro `ReferenceError: window is not defined`, há alguma solução para estre problema? Valeu!

### Edit: Fiz um `workaround`

`cep.ts`:
```ts
// types
interface CEP {
	cep: string;
	state: string;
	city: string;
	street: string;
	neighborhood: string;
}

// cep function
let cepPromise: (cep: string | number) => Promise<CEP>;

// checks for window
if (typeof window !== 'undefined') {
	// client cep
	cepPromise = require('cep-promise/dist/cep-promise-browser');
} else {
	// server cep
	cepPromise = require('cep-promise/dist/cep-promise');
}

// exports cep promise
export { cepPromise };
```

**Comment by lucianopf** [comment]
A ideia de ter as 2 dists distintas era pra diminuir especialmente o bundle do Browser, pelo visto agora ta rolando treta com o Parcel no Node, vou atacar aqui pra ver se resolvo ainda quebrando os dists, se precisar a gnt volta dessa forma que vc comentou =/

**Comment by Rechdan** [comment]
> A ideia de ter as 2 dists distintas era pra diminuir especialmente o bundle do Browser, pelo visto agora ta rolando treta com o Parcel no Node, vou atacar aqui pra ver se resolvo ainda quebrando os dists, se precisar a gnt volta dessa forma que vc comentou =/
Não sabia que era de outra forma antigamente, foi a primeira vez que usei essa lib e gostei bastante, o workaround que utilizei ali pode ser uma alternativa até mesmo pra uma futura versão, o que acha?

**Comment by lucianopf** [comment]
Era justamente assim antes! hehehe
Então, tudo depende do tamanho bundle do browser tbm que na real não precisa conter as dependências do Node.

Apesar de no runtime ele carregar somente um módulo o pacote tem que levar tudo se não houver essa distinção o bundle do browser fica maior do que o necessário.

To dando uma olhadinha aqui pra ver se rola manter como é hoje e se não der certo a gnt volta pra essa sua abordagem :grimacing: :metal:

**Comment by lucianopf** [comment]
Mestre @Rechdan consegue me dar uma ajudinha pra reproduzir o erro? :pray: 

Tentei aqui um js simples usando o parcel pra buildar com target node e deu certo, provavelmente temos alguma diferença no processo de build, correto?

![help](https://user-images.githubusercontent.com/8251208/88810668-0bb10a80-d18c-11ea-824e-f04e7bc9b271.png)

**Comment by Rechdan** [comment]
Opa, eu usei o Parcel na versão `1.12.4` e o comando de build foi o seguinte: `parcel watch ./src/server/index.ts --out-dir ./dist --out-file server.js --target node --bundle-node-modules --log-level 4 --no-autoinstall --no-hmr --no-cache`

Depois rodei o build com `node ./dist/server.js` e, se me lembro bem, já deu o erro.

**Comment by lucianopf** [comment]
Boooa mestre, achei onde ta rolando a treta é aqui `--bundle-node-modules`

Vou dar uma lidinha pra entender o que ele ta fazendo, se quiser já ir dando uma moral pra ajudar a entender pq usa essa flag já vai ajudar :grimacing:

**Comment by Rechdan** [comment]
Opa, eu uso ela pra não precisar instalas as dependências no ambiente de produção, apenas rodo o arquivo `server.js` e nada mais, essa flag é apenas pra isso hahaha

**Comment by lucianopf** [comment]
Como eu amo Open-Source!! :heart: :joy: 

Olha que massa mano!!

Essa função é responsável por no build com módules identificar de onde deve pegar os módulos:

https://github.com/parcel-bundler/parcel/commit/def821f20e410c523ecc1320be9ef0ff858e97bc#diff-3d0a12cd4bfd4e84137efd9f1ec9555dR278-R347

Repara aqui:

```js
    let main = [pkg.source, browser, pkg.module, pkg.main].find(
      entry => typeof entry === 'string'
    );
```

Ele na real pega na ordem do array de onde ta vindo o módulo.

1. package.json#source
2. browser (que nesse caso é null)
3. package.json#module
4. package.json#main

Aqui no `cep-promise/package.json` a gnt tem definido

```json
  "module": "dist/cep-promise-browser.min.js",
```

Mudando essa definição pra usar a do Node tudo volta a funcionar normal :raised_hands: 

Agora só preciso dar uma pesquisada no repo pq deixamos o `module` apontando pra versão do Browser pra entender se podemos alterar isso sem consequências ou se na real o passo é criar um PR no Parcel :grimacing:

**Comment by Rechdan** [comment]
Sensacional, não conhecia como ele funcionava, muito interessante saber que é assim e muito obrigado pela atenção, Luciano! Acabou de ganhar um seguidor! Hahaha 😁

**Comment by lucianopf** [comment]
@Rechdan fiz vários testes aqui e todos pareccem ter dado certo, mas antes de publicar primeiro queria que vc fizesse um teste e o @filipedeschamps desse uma conferida :eyes: :grimacing: 

Pra testar vai lá no seu package.json e nas dependências troca lá a versão pra

```json
  "cep-promise": "https://github.com/filipedeschamps/cep-promise/archive/v3.0.10-rc1.tar.gz"
```

E me confirma pfv se deu bom :pray: :grimacing:

**Comment by Rechdan** [comment]
@lucianopf agora deu um outro erro, segue ele:
```
Error [CepPromiseError]: require(...) is not a function
    at new r (D:\...\dist\server.js:157955:5467)
    at S (D:\...\dist\server.js:157955:4297)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Object.<anonymous> (D:\...\dist\server.js:158033:19)
    at async Promise.all (index 1)
    at async Promise.all (index 0)
    at async Promise.all (index 0)
    at async Promise.all (index 0)
    at async Object.exports.validateRegisterCompany (D:\...\dist\server.js:158120:16) {
  type: undefined,
  errors: undefined
}
```

**Comment by lucianopf** [comment]
Eita mestre, aqui funcionou direitinho :thinking: 

Só pra garantir, vc matou o `node_modules` e mandou instalar tudo dnv?

![eita](https://user-images.githubusercontent.com/8251208/88837122-298f6700-d1ae-11ea-8639-7becb44e0cdb.png)

**Comment by Rechdan** [comment]
Não tinha apagado a `node_modules` antes, mas mesmo depois que fiz continuou o erro, será que é a versão do meu Node? Qual versão é o seu?

**Comment by lucianopf** [comment]
To usando a `v8.9.4` e vc? 

Gente que loucura isso hahahaha

**Comment by Rechdan** [comment]
Eita, eu to usando a LTS `v12.18.3`, que estranho kkkkk

Inclusive puis no projeto apenas isso:
```ts
cepPromise('12041-108')
	.then((cep) => console.log({ cep }))
	.catch((ex) => console.error({ ex }));
```
E ainda sim continuo com o erro

**Comment by lucianopf** [comment]
Tava com a build errada aqui :man_facepalming: 

Consegui reproduzir e to tentando entender o que ta roland agora =/

É mto bizarro ele reclamar que não tem require, especialmente pq a gnt ta usando type=node :face_with_head_bandage:

**Comment by Rechdan** [comment]
Nem me fala man, achei super estranho também, nunca vi dar esse bug antes lol

**Comment by lucianopf** [comment]
Mestre @Rechdan tenta pfv 

```
  "cep-promise": "https://github.com/filipedeschamps/cep-promise/archive/v3.0.10-rc1.tar.gz"
```

Remove o node_modules e os arquivos de lock e tenta instalar dnv pfv :pray: :pray:

**Comment by Rechdan** [comment]
Testado e **SUPER** aprovado! Agora foi sem problemas algum!

**Comment by lucianopf** [comment]
Opaaa que bom que deu certo @Rechdan !!

Vou agora acertar o PR então, tentar corrigir o CI e lançar uma nova versão oficial, daí te aviso quando tiver pronto! :grimacing:

**Comment by Rechdan** [comment]
Perfeito @lucianopf, estarei no aguardo aqui! Muitíssimo obrigado pelo suporte meu caro! 😁

**Comment by filipedeschamps** [comment]
Sensacional a interação de vocês! Feito o merge do PR sobre essa issue na branch `4.0.0` que está aberta ainda https://github.com/filipedeschamps/cep-promise/pull/180

**Comment by filipedeschamps** [comment]
Feito o merge da branch `4.0.0` 👍
