### ISSUE TITLE
Erro de CORS no proxier.now.sh v3.x.x da lib

### ISSUE THREAD

**Issue by jrmarqueshd** [filipedeschamps/cep-promise#182]
Olá, recentemente estou notando no console que está ocorrendo alguns erros de CORS na rota que usa o proxier.now.sh.

O erro é o seguinte :
> Access to fetch at 'https://proxier.now.sh/api?url=https://apps.correios.com.br/SigepMasterJPA/AtendeClienteService/AtendeCliente' from origin 'URL DO SITE' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

Estou utilizando a versão 3.0.9

**Comment by filipedeschamps** [comment]
@jrmarqueshd show! O Proxier está sendo desativado, mas a boa notícia é que acabamos de lançar a versão `4.0.0` que implementa o BrasilAPI como provider e ele possui CORS liberado.

Apesar essa nova versão ser uma major release, ela não traz breaking change na interface pública do módulo, somente na versão do Node.js (que agora a mínima necessária para o build pelo menos é a `10.x`).

Você poderia testar com essa nova versão `4.0.0` e ver se o erro persiste?

Muito obrigado 🤝

**Comment by jrmarqueshd** [comment]
Fala @filipedeschamps, fix o update da versão v3.0.x da lib para a v4.0.0 e isso realmente solucionou o problema de CORS, já que não estão mais utilizando o proxier.now.sh!

Acredito que já possamos fechar essa issue, uma vez que o problema já está solucionado.

Obrigado. 😃

**Comment by filipedeschamps** [comment]
Sensacional meu caro! Qualquer coisa que precisar, só abrir uma issue 👍
