### ISSUE TITLE
Some vulnerabilities require your attention to resolve

### ISSUE THREAD

**Issue by klaveren** [filipedeschamps/cep-promise#185]
Hi Devs,

In a few days ago the npm audit security report identify a security problem Denial of Service  in the  node-fetch. 
The notify is here https://npmjs.com/advisories/1556. And the solution is update the node-fetch to version => 3.0

You have some idea to update the package in the near future? 

Thanks

**Comment by filipedeschamps** [comment]
@klaveren going to release a patch today, thanks for the heads-up 🤝

**Comment by klaveren** [comment]
thank you so much in advance @filipedeschamps.

**Comment by ehauzman** [comment]
@filipedeschamps ainda há uma vulnerabilidade na dependência node-fetch:

                       === npm audit security report ===                        


                                 Manual Review                                  
             Some vulnerabilities require your attention to resolve             
                                                                                
          Visit https://go.npm.me/audit-guide for additional guidance           


  Low             Denial of Service                                             

  Package         node-fetch                                                    

  Patched in      >=2.6.1 <3.0.0-beta.1|| >= 3.0.0-beta.9                       

  Dependency of   cep-promise                                                   

  Path            cep-promise > node-fetch                                      

  More info       https://npmjs.com/advisories/1556                             

found 1 low severity vulnerability in 1945 scanned packages
  1 vulnerability requires manual review. See the full report for details.

**Comment by filipedeschamps** [comment]
@ehauzman está sendo discutido aqui: https://github.com/filipedeschamps/cep-promise/pull/186

Tivemos um problema com um dos providers que não fazia os testes passarem. Mas o @lucianopf encontrou uma alternativa e eu dei uma sugestão em cima disso, mas como é um patch de segurança acredito melhor avançar de qualquer jeito então.

O merge e a publicação no npm não passam de hoje, fechado? 🤝

**Comment by ehauzman** [comment]
Você é o cara @filipedeschamps

**Comment by filipedeschamps** [comment]
Publicado patch de segurança na versão `4.0.1` 👍 obrigado em especial ao @lucianopf por conseguir liberar os testes 🤝
