### ISSUE TITLE
Erro ao executar nova versão 4.0.1

### ISSUE THREAD

**Issue by rodrigopasc** [filipedeschamps/cep-promise#187]
Oi, tudo bem?

Após atualizar para a versão 4.0.1, o seguinte erro é exibido (ao executar a aplicação):

```
Failed to compile.
./node_modules/cep-promise/dist/cep-promise-browser.min.js
Module not found: Can’t resolve ‘unfetch’
```

Visualizei que no yarn.lock realmente não consta a dependência `unfetch`, como visto abaixo:

```
cep-promise@^4.0.0:
  version "4.0.1"
  resolved "https://registry.yarnpkg.com/cep-promise/-/cep-promise-4.0.1.tgz#9a17d32c95a7c1b256935aa20f8eb862c919c323"
  integrity sha512-+47Zv9XEPNbeFaIC/Ewr8PjdKvDAKnNxRKeIeBZv69eCfuOej5v1C8/jABROgdn52zFiTHVJE14RoCgzHDfkmQ==
  dependencies:
    node-fetch "2.6.1"
```

Deixei a versão fixa como 4.0.0 e o problema foi resolvido, mas curiosamente, o yarn.lock voltou a conter a dependência `unfetch`:

```
cep-promise@^4.0.0:
  version "4.0.0"
  resolved "https://registry.yarnpkg.com/cep-promise/-/cep-promise-4.0.0.tgz#252bb8f378b4156d3dd53d40913c0fdd2c2a61e7"
  integrity sha512-4n1v1JJcZXDMK0QPUMzmPtC5zJUgujGpkeT9Ko2a6zA8W37NXYGXDBwXCDUbQd7EtMiNw/Wmn4c6OpczWQrYVg==
  dependencies:
    node-fetch "2.6.0"
    unfetch "4.1.0"
```

Obrigado. :D

**Comment by filipedeschamps** [comment]
Show, verificando! Não uso yarn, mas achei estraho no seu log isso:

```
cep-promise@^4.0.0:
  version "4.0.1"
```

Vou verificar 🤝

**Comment by filipedeschamps** [comment]
@rodrigopasc eu fiz um projeto de testes aqui, instalando o cep-promise pelo yarn e rodando uma consulta e não tive erros.

Pelo fato do projeto não ter um `yarn.lock`, será que é algum cache em algum lugar? Por favor, me ajude com um teste, deletando a pasta `node_modules` e este `yarn.lock` e reinstale todas as dependências novamente.

Se isso não funcionar, você poderia me dar um pouco mais de contexto em como está instalando/atualizando a dependência?

Muito obrigado 🤝

**Comment by ehauzman** [comment]
@filipedeschamps também tive o mesmo erro aqui! 
Após atualizar utilizando o comando 'npm update', o cep-promise foi atualizado para a versão 4.0.1, mas recebo o erro ao compilar:
./node_modules/cep-promise/dist/cep-promise-browser.min.js
Module not found: Can't resolve 'unfetch' in '..\node_modules\cep-promise\dist'

**Comment by filipedeschamps** [comment]
De fato, eu estava testando a versão Node.js, encontrei o que está acontecendo e essa transformação está sendo feita dentro do `rollup.config.js`

![image](https://user-images.githubusercontent.com/4248081/94226652-fe26b100-feac-11ea-9e0a-16c184f63f8d.png)

Vou reinserir essa dependência agora e tem a ver com esse PR aqui: https://github.com/filipedeschamps/cep-promise/pull/178

**Comment by filipedeschamps** [comment]
Turma, publicado `cep-promise@4.0.2` que adiciona o `unfetch` novamente 👍 

Vocês poderiam testar para ver se o replace agora está 100% funcionando no fluxo de vocês?

**Comment by ehauzman** [comment]
Agora está funcionando corretamente @filipedeschamps .
Obrigado!

**Comment by rodrigopasc** [comment]
Agora também está funcionando perfeitamente aqui!

Desculpa ter demorado para responder.

Muito obrigado, @filipedeschamps!

**Comment by filipedeschamps** [comment]
Showwwwww 😍 fechando a issue e muito obrigado por reportar o erro! Não hesitem em fazer de novo quando esbarrarem em algo 🤝 👍
