### ISSUE TITLE
Checar se existe item no array

### ISSUE THREAD

**Issue by chrisbenseler** [filipedeschamps/cep-promise#29]
Filipe,

na função "extractValuesFromParsedXML" tem trechos assim, para definir aquele objeto "addressObject":

neighborhood: addressValues['bairro'][0]

não cheguei a ver o xml de retorno dos correios, mas é garantido que sempre vai ter um array com pelo menos um elemento para todas chaves de addressValues? Não seria mais seguro fazer uma checagem?
Algo como

neighborhood: addressValues['bairro'] && addressValues['bairro'].length > 0 ? addressValues['bairro'][0] : "" //ou null

?

*ou ainda uma checagem mais profunda se o addressValues['chave'] é um array, como discutida por exemplo aqui: http://stackoverflow.com/questions/5941706/javascript-detect-if-argument-is-array-instead-of-object-node-js

Não quero fazer um PR se essa for uma feature que não fará sentido (no caso, se o xml sempre retornar um array)

**Comment by filipedeschamps** [comment]
@chrisbenseler faz TOTAL sentido o que você falou. Deveria ser garantido que venha, mas precisamos nos proteger. Um PR é extremamente bem vindo, ma sugiro fazer utilizando o `get` do lodash, por exemplo como é feito aqui:

https://github.com/filipedeschamps/cep-promise/blob/master/src/cep-promise.js#L82

É só colocar o caminho do objeto que o lodash dá um jeito de achar ou não o valor.

O que acha? 👍

**Comment by chrisbenseler** [comment]
Boa! Não conhecia essa.
Amanhã faço um PR com isso então!

**Comment by thebergamo** [comment]
No caso, se não existe nenhum item no array ou se o array não existe o proprio get do lodash consegue não estourar uma excessão e apenas retorna nulo.

**Comment by filipedeschamps** [comment]
Feito merge pelo PR https://github.com/filipedeschamps/cep-promise/pull/31
