### ISSUE TITLE
Fallback ao apps.correios.com.br

### ISSUE THREAD

**Issue by lucianopf** [filipedeschamps/cep-promise#34]
@filipedeschamps Seria interessante implementar um fallback a API do correios usando tipo o https://viacep.com.br/?

Já ouvi boatos que essa API do correios não é muito estável.. rsrs

**Comment by filipedeschamps** [comment]
Com certeza absoluta @lucianopf ! Você peitaria um PR para discutirmos como deixar a arquitetura disso simples?

**Comment by lucianopf** [comment]
Fiz um pouco na pressa mas assim que tiver um tempinho otimizo e crio testes pra isso, mas a ideia seria mais ou menos isso Filipe [link pro meu commit.](https://github.com/lucianopf/cep-promise/commit/3ecc0a7757656b198b8d4c5e826e297af4562ece)

**Comment by filipedeschamps** [comment]
Closed by https://github.com/filipedeschamps/cep-promise/pulls
