### ISSUE TITLE
Normalizar as interfaces de erro

### ISSUE THREAD

**Issue by filipedeschamps** [filipedeschamps/cep-promise#37]
Agora que temos múltiplos fornecedores desenvolvido pelo @lucianopf para versão `2.0` precisamos normalizar a interface de erro.

Hoje ela está alternando entre um objeto e um array:

``` js
cep().catch(console.log)

{ type: 'type_error',
  message: 'Você deve chamar o construtor utilizando uma String ou Number',
  service: undefined }
```

``` js
cep('99999999').catch(console.log)

[ { type: 'range_error',
    message: 'CEP inválido',
    service: 'viacep' },
  { type: 'range_error',
    message: 'CEP não encontrado na base dos Correios',
    service: 'correios' } ]
```

Fora isso, fica aberta a pauta: qual a melhor interface de erro para minha aplicação tratar? Por exemplo:

 1. Um array de objetos dos erros
 2. Um objeto em que a chave é o serviço e o valor é o erro (e quando for erro por validation colocar o service algo como `library`
 3. Um objeto onde o `type` é a chave
 4. Um objeto que possui uma chave `errors` e dentro dela um array de erros
 5. ?

**Comment by lucianopf** [comment]
Eu pensei bastante em normalizar o erro em um objeto, mas estava tendo dificuldades, já que os serviços possuem formas bem diferentes de tratar erros. =/
Por exemplo o Viacep responde Bad Request (400) pra quase tudo.. rsrs
Por isso optei por meter um array de erros, o problema é que esqueci de normalizar o array.. :laughing: 

Vou pensando tbm formas melhores de lidar com os erros e se tiver uma ideia melhor volto aqui! hahah

Vou me dar o prazo de uma semana pra tentar pensar em algo, caso não ocorra, implemento o que ficar decidido aqui! :smile:

**Comment by filipedeschamps** [comment]
@derekstavis este foi o caso que te falei sobre qual melhor interface de erro.

**Comment by filipedeschamps** [comment]
@felquis, @grvcoelho e @MarcoWorms alguma sugestão? Nos ajudem please :)

**Comment by MarcoWorms** [comment]
Na minha experiência lidar com array de objetos é o mais fácil. Isso pode váriar sempre dependendo de como vc quer usar esses erros, mas se o intuito é ser uma lista de erros eu seguiria a simples lógica: uma lista é uma array e um erro é um objeto, portanto uma lista de erros = array de objetos. Eu também prefiro essa abordagem pois fica extremamente fácil mexer nessa lista usando `map`, `filter` e `reduce`. 

Acho que o jeito mais fácil de vc achar essa solução caso não goste do array de objetos é pensar qual vai ser o usecase disso usando uma abordagem meio TDD. Eu não consigo imaginar um situação onde a array de objetos vai complicar sua vida, mas com certeza essa situação existe :)

**Comment by filipedeschamps** [comment]
PR aceito, vou lhe dar write no repo 👍
