### ISSUE TITLE
Sugestão de uma mudança no gif do readme pra ficar menos frenético

### ISSUE THREAD

**Issue by MarcoWorms** [filipedeschamps/cep-promise#44]
O gif atual do readme está muito rápido e na minha opinião incomoda quando fica na tela. Por acaso vcs concordam em mudar? Fiz 5 versões com velocidades diferentes como sugestão:

1:
![1](http://piskel-imgstore-b.appspot.com/img/6b725cae-8c31-11e6-b5b7-012e3c025933.gif)

2:
![2](http://piskel-imgstore-b.appspot.com/img/41faae9c-8c31-11e6-854e-012e3c025933.gif)

3:
![3](http://piskel-imgstore-b.appspot.com/img/30b8141c-8c31-11e6-a3d5-012e3c025933.gif)

4:
![4](http://piskel-imgstore-b.appspot.com/img/52f7987d-8c31-11e6-91bd-012e3c025933.gif)

5:
![5](http://piskel-imgstore-b.appspot.com/img/5afe59ab-8c31-11e6-903e-012e3c025933.gif)

**Comment by filipedeschamps** [comment]
HAHAHAHHA é a parte frenética é o pattern que eu uso para os meus módulos, veja o rss-feed-emitter:

https://github.com/filipedeschamps/rss-feed-emitter

![logo](https://raw.githubusercontent.com/filipedeschamps/rss-feed-emitter/master/content/logo.gif)

Acho que é essa loucura que traz o charme :)

**Comment by lucianopf** [comment]
Acho engraçado tbm! hahahah

**Comment by MarcoWorms** [comment]
haahah ok!
