### ISSUE TITLE
Publicar versão no NPM

### ISSUE THREAD

**Issue by lucianopf** [filipedeschamps/cep-promise#49]
@filipedeschamps Acho que essa versão já rola de publicar no npm, não? 😬

**Comment by filipedeschamps** [comment]
É bem possível que esse finds façamos o bump do 2.0 👍

**Comment by filipedeschamps** [comment]
Dois pontos para publicarmos a `2.0`:

- [ ] Fazer o merge do suporte ao browser https://github.com/filipedeschamps/cep-promise/pull/50
- [ ] Alterar a interface pública de Object para Error https://github.com/filipedeschamps/cep-promise/issues/51

Está bem próximo :)

**Comment by filipedeschamps** [comment]
@lucianopf adicionei um item: https://github.com/filipedeschamps/cep-promise/pull/56

**Comment by filipedeschamps** [comment]
Feito release no npm da versão `2.0`. Belo trabalho senhores @lucianopf @MarcoWorms  👍
