### ISSUE TITLE
Alterar a interface pública de Object para Error

### ISSUE THREAD

**Issue by filipedeschamps** [filipedeschamps/cep-promise#51]
Uma boa library expõe erros de forma pública com a instância de um Error ou de um custom Error, pois há alguns benefícios interessantes nisto, como por exemplo, ter o call stack exposto.

Vou tentar arranjar um tempinho ao longo desta semana para trocar todos os erros e testes de um Object para um Error e aproveitar a versão 2.0.

**Comment by lucianopf** [comment]
Eu cheguei a pensar nisso tbm, mas pensei em fazer com custom Error, só não sei ainda como iremos lidar com o erro final, que no caso é um array de erros. =/
Talvez ele tbm seja um custom com um atributo errors.. 😁

**Comment by lucianopf** [comment]
Concluido com maestria em #55
