### ISSUE TITLE
Integração com google

### ISSUE THREAD

**Issue by leorjbrz** [filipedeschamps/cep-promise#59]
Apenas uma sugestão de uma terceira opção de busca utilizando o google
Exemplo:

```
//https://developers.google.com/maps/documentation/javascript/examples/geocoding-reverse
return $http.get('//maps.googleapis.com/maps/api/geocode/json', {
    params: {
        address: '20560160',
        language: 'pt-BR',
        components: 'country:BR',
        location_type: 'ROOFTOP',
        result_type: 'street_address',
        sensor: false
    }
});
```

Exemplo de retorno do google:

```
$scope.logradouro = {};
var arrAddress = $item.address_components;
for (var i = 0; i < arrAddress.length; i++) {
    if (arrAddress[i].types[0] === "route") { $scope.logradouro.logradouro = arrAddress[i].long_name }
    if (arrAddress[i].types[0] === "street_number") { $scope.logradouro.numero = arrAddress[i].long_name }
    if (arrAddress[i].types[0] === "sublocality" || (arrAddress[i].types.length > 0 && arrAddress[i].types[1] == "sublocality")) { $scope.logradouro.bairro = arrAddress[i].long_name }
    if (arrAddress[i].types[0] === "locality") { $scope.logradouro.cidade = arrAddress[i].long_name }
    if (arrAddress[i].types[0] === "administrative_area_level_1") { $scope.logradouro.uf = arrAddress[i].short_name }
    if (arrAddress[i].types[0] === "postal_code") { $scope.logradouro.cep = arrAddress[i].long_name; console.log(arrAddress[i]); }
}
```

Vejam se conseguem usar o openstreetmap tbm, mas achei os parametros meio furados, traz dados diversos... tem que debulhar
//http://wiki.openstreetmap.org/wiki/Nominatim#Parameters

abraços!

**Comment by filipedeschamps** [comment]
Caramba, não sabia que eles tinham api para isso!

**Comment by filipedeschamps** [comment]
@leorjbrz topa fazer um PR?

**Comment by MarcoWorms** [comment]
Caso o OP não esteja afim de fazer, eu posso implementar isso semana que vem :)

**Comment by lucianopf** [comment]
To meio sem tempo de contribuir essa semana mas precisando de ajuda é só chamar @MarcoWorms !! 😁

**Comment by MarcoWorms** [comment]
Estou fazendo agora, qualquer coisa eu abro uma branch :cake:

**Comment by MarcoWorms** [comment]
Eu só estou tendo problema em extrair o nome da rua, mesmo enviando o 'result_type' como 'street_address' ele ainda não está me dando o nome da rua :/

Exemplo de response:
```javascript
[ { long_name: '05679-010',
    short_name: '05679-010',
    types: [ 'postal_code' ] },
  { long_name: 'Jardim Panorama',
    short_name: 'Jardim Panorama',
    types: [ 'political', 'sublocality', 'sublocality_level_1' ] },
  { long_name: 'São Paulo',
    short_name: 'São Paulo',
    types: [ 'locality', 'political' ] },
  { long_name: 'São Paulo',
    short_name: 'São Paulo',
    types: [ 'administrative_area_level_2', 'political' ] },
  { long_name: 'State of São Paulo',
    short_name: 'SP',
    types: [ 'administrative_area_level_1', 'political' ] },
  { long_name: 'Brazil',
    short_name: 'BR',
    types: [ 'country', 'political' ] } ]

```

**Comment by lucianopf** [comment]
Da push no branch aí que amanhã cedo eu tento te ajudar tbm! 😁

**Comment by MarcoWorms** [comment]
Eu fiz uma branch https://github.com/filipedeschamps/cep-promise/tree/add-google-service , vou dormir agora, amanhã eu tento resolver esse problema do nome da rua :)

**Comment by MarcoWorms** [comment]
ps: eu estava compilando o google.js com o 'build-node' e rodando o service na mão no final do arquivo para testar

**Comment by lucianopf** [comment]
É... to começando a achar que com uma requisição só não é possível.. rsrs

**Comment by MarcoWorms** [comment]
Talvez precise de API key ou precise fazer uma segunda requisicao com o placeId né?

**Comment by lucianopf** [comment]
Mesmo com a key ainda precisa da segunda requisição fazendo o reverse, acho que não é tão válido não :cry: 

Dps vou dar uma olhada nessa do streetmap.

**Comment by MarcoWorms** [comment]
Troquei ideia com o @filipedeschamps ele achou válido 2 requests pois o google e uma opcao segura, vou ver se rola com o segundo request.

**Comment by MarcoWorms** [comment]
Acabei de descobrir que alguns ceps nem sequer retornam resultado, além disso mesmo com varias requests não consegui o nome da rua.

**Comment by MarcoWorms** [comment]
Se quiser dar uma olhada, ontem eu achei uma parte obscura da documentação que é sobre esse request https://developers.google.com/maps/documentation/geocoding/intro#GeocodingRequests

ja tentei varias coisas mas nenhuma foi consistente ou me retornou o nome da rua :/

**Comment by MarcoWorms** [comment]
O problema da inconsistencia de receber resultados pode ser resolvido usando o component 'country:BR', mas por algum motivo a google vai mandar o cep sem os ultimos 3 digitos (e ainda assim não vem nome da rua)

**Comment by MarcoWorms** [comment]
Quando eu faço uma request identica ao exemplo citado pelo @leorjbrz ainda assim nao recebo nem nome da rua nem cep completo, talvez não valha a pena integrar essa rota.

**Comment by lucianopf** [comment]
Eu consegui pegando a latitude e longitude da primeira e usando na segunda com latlng=xxx , xxx mas tava com pouquíssima precisão..

Acho melhor abortar mesmo.. =(

**Comment by MarcoWorms** [comment]
eu fiz o mesmo que vc e tive o mesmo resultado, vem muito resultado :(, eu vou tentar filtrar o resultado usando os dados anteriores

**Comment by MarcoWorms** [comment]
Eu to tentando resolver o problema mas me ajudaria muito ter as funções de promise da bluebird. @filipedeschamps e colaboradores, o que vcs acham de usar bluebird?

**Comment by lucianopf** [comment]
Eu removi o bluebird pq a gnt só tava usando o Promise.any dele, já que as demais funcionalidades de Promise já estão tendo pollyfill pelo BabelJS, daí reduziu um bocado o tamanho do bundle final do web, mas nada que impeça a gnt de voltar a usar ele se necessário! 🤓 

Até pq dps a gnt da um jeito de ou substituir ou reduzir mais o bundle final. ^^

**Comment by MarcoWorms** [comment]
ok, eu vou usar entao só pra tentar resolver e depois a gente ve como troca :)

**Comment by MarcoWorms** [comment]
como estamos fazendo para lidar com error handling sem a bluebird? não estavamos usando pra isso? o @derekstavis vai abrir uma issue sobre isso pq ele que percebeu

**Comment by lucianopf** [comment]
Sim, antes a gnt tava usando o catch(errorQuery, function), daí como a redução do tamanho era importante e era possível abrir mão dessa feature eu voltei ao catch padrão tratando condicionalmente. Link pro PR #58

Mas novamente, se for algo que vá agregar ao projeto não vejo mal nenhum em voltar a usar o bluebird, até pq eu sempre usei ele e sou fã da lib! rsrs

Git taí pra isso! rsrs
Bora testar!!! ^^

**Comment by MarcoWorms** [comment]
Então, eu consegui implementar a segunda request mas a precisão ficou ridícula

```
fetchGoogleService('05679010')
fetchGoogleService('86900000')
fetchGoogleService('88058512')
```

isso gerou 3 resultados diferentes: 1 certo, 1 incompleto, e o terceiro nem sequer achou o cep

```
Unhandled rejection ServiceError: Cannot read property 'geometry' of undefined
---
{ cep: '86900000',
  state: 'PR',
  city: 'Jandaia do Sul',
  neighborhood: 'not-found',
  street: 'Unnamed Road' }
---
{ cep: '05679010',
  state: 'SP',
  city: 'São Paulo',
  neighborhood: 'Jardim Panorama',
  street: 'Rua Armando Petrella' }
```

subi o hack que eu fiz na branch, se quiserem mexer fiquem a vontade. Não senti muita firmeza na api pois temos que achar uma geolocalizacao e depois bater com resultados próximos dessa localização. A única maneira seria usando uma api key mas acho inviável pois ela ia explodir.

**Comment by lucianopf** [comment]
É.. ta se mostrando inviável msm =/

Amanhã com a cabeça mais fresca dnv tento pensar em alguma coisa tbm.. 😬

**Comment by MarcoWorms** [comment]
Pensei numa última tentativa, vou tentar fazer agora :D

**Comment by MarcoWorms** [comment]
Consegui! Resolvi todas as inconsistencias que eu achei, agora retorna todos os ceps com os nomes da rua, precisa refatorar mas o essencial ta funcionando :D

**Comment by MarcoWorms** [comment]
Bad news: testei mais ceps e deu mais inconsistencia, por hoje vou deixar de lado, amanhã continuo na missão.

**Comment by MarcoWorms** [comment]
Ainda temos a seguinte solução: quem quiser usar a google retira uma chave de api e coloca no cep-promise :)

**Comment by filipedeschamps** [comment]
Sobre o bluebird de fato, tiramos um monte de dependência e conseguimos chegar em 16k (sem compressão) no browser. Talvez o que podemos continuar a fazer é extrair dele apenas as funcionalidades que precisamos 👍 

Sobre o Google, puts que pena que ele ta doidão! Ter ele como fallback numa blackfriday ia ser do caralho :)

**Comment by lucianopf** [comment]
[Endereço real](http://maps.googleapis.com/maps/api/geocode/json?address=Antonio%20Borges%20522)

Seguindo seu código ta fazendo assim:
[Primeira busca](http://maps.googleapis.com/maps/api/geocode/json?address=29065250)
[Segunda busca](http://maps.googleapis.com/maps/api/geocode/json?latlng=-20.2752357,-40.2873054)

Que tbm tá errado :cry: 
Puts, seria muito massa mesmo, mas nem fazendo média dos limites das latitudes to conseguindo chegar perto do meu enderço.. :sob: 

Ta triste esse reverse geocoding do Googri =/

Como usar uma api key iria aumentar a precisão @MarcoWorms ? 
Eu antes tava imaginando em usar o place_id, mas mesmo assim ta vindo exatamente como o primeiro resultado, e se vc adicionar result_type tem como resposta `"error_message" : "Invalid request. Only one of the 'place_id' or 'result_type' parameters are allowed."` :face_with_head_bandage: 


Já quanto ao uso de .props, como eu disse sou totalmente fã do bluebird e da abordagem de retornar um objeto mas se for pelo bem da aplicação pode trocar a abordagem por um .all simples ou rolar um:
```
Promise.props = (obj) => {
  return Promise.all(Object.keys(obj).map((el) => obj[el]))
    .then((res) => {
      Object.keys(obj).forEach((el, id) => {
        obj[el] = res[id]
      })
      return obj
    })
}
```
Fiz rapidão e ignorei um bocado de coisas, tipo ordem caso seja distribuído, mas taí funcionando por agora.. hahaha

**Comment by MarcoWorms** [comment]
@lucianopf com uma apikey vc pode usar o location=ROOFTOP na segunda request com latlng (provavelmente na primera tambem) e aí vc pega o endereço exato.

**Comment by lucianopf** [comment]
Usando `location=ROOFTOP` em ambas ainda ta dando bem errado pra meu enderço =(
:weary: :sweat:

**Comment by MarcoWorms** [comment]
poxa, até trocando só a segunda request pra usar key ta dando errado? Então acho que acabou D:

**Comment by lucianopf** [comment]
Sim, deu outro endereço, mas ainda assim foi errado :sob:

**Comment by MarcoWorms** [comment]
:disappointed: tão perto mas tão longe hahahaha

**Comment by filipedeschamps** [comment]
hahahah sem problemas senhores! Foi um ótimo desenvolvimento de qualquer forma 👍

**Comment by filipedeschamps** [comment]
Passamos o blackfriday ilesos :) fechando a issue

**Comment by Renatomsilva** [comment]
@filipedeschamps @MarcoWorms @lucianopf Dei uma olhada na issue. E realmente passei por todas estas dores quando resolvi utilizar o Maps. Vou pegar a solução que criei e montar alguns testes com os diversos CEPs de todas as regiões do Pais. Me lembro que na ultima amostragem que fiz para o projeto Mudamos.org que é um projeto de votação de leis iniciativas popular com mais de 500 mil cadastrados. Nossa assertividade na busca estava muito boa. Inclusive até busca reversa eu fiz para o projeto. Assim que fizer os testes posto aqui . Ai podemos avaliar se podemos reabrir a issue.

**Comment by filipedeschamps** [comment]
Sensacional @Renatomsilva fechado!!

**Comment by hugows** [comment]
@Renatomsilva Oi renato - desculpe perguntar aqui, não sei outra maneira, mas tenho uma curiosidade: em um projeto grande como o seu, em geral as quotas dão problema? Vcs precisam pagar "do bolso"? Essa API do Google é fantástica, mas se gerar custo acho que o cliente vai preferir uma solução mais tosca...

**Comment by renatomartinszup** [comment]
@hugows Tivemos que pagar sim , a parte free não deu conta e desculpe pela demora

**Comment by renatomartinszup** [comment]
Estava falando desta thread com um pessoal hoje 2020 . Vou precisar retomar uns testes com a API do Google e vamos ver se continua na mesma . Se tiver algum progresso eu atualizo aqui.
