### ISSUE TITLE
Entramos no Trending JavaScript do Github de novo :)

### ISSUE THREAD

**Issue by filipedeschamps** [filipedeschamps/cep-promise#60]
https://github.com/trending/javascript

Tá lá em baixo, mas está haha 👍 

![image](https://cloud.githubusercontent.com/assets/4248081/19720684/fa1f4296-9b4d-11e6-8f3b-85a6bf5277b0.png)

**Comment by lucianopf** [comment]
😱👏🎉
Uhuuu, parabéns!!!!

Já e

**Comment by MarcoWorms** [comment]
Ja ouviram falar daquela lib de js cep-promise?

**Comment by filipedeschamps** [comment]
Olha que legal 👍 

![image](https://cloud.githubusercontent.com/assets/4248081/20117617/85d5e7be-a5e8-11e6-9b33-6b49745c7161.png)

@lucianopf @MarcoWorms
