### ISSUE TITLE
Adicionar guia de contribuição

### ISSUE THREAD

**Issue by pedrro** [filipedeschamps/cep-promise#65]
Olá, é possível que seja feito um guia para contribuição no projeto?

Alguns exemplos de informações que podem ser colocado:
- Como iniciar o projeto localmente
- Estrutura do projeto
- Como abrir PR's
- Nome dos commit's
- etc...

**Comment by lucianopf** [comment]
Seria ótimo!!

Posso encabeçar ou ajudar se quiser @pedrro :grin:

**Comment by pedrro** [comment]
Massa! Posso mandar um PR hoje com um escopo e aí a gente vai alterando, o que acha?

**Comment by filipedeschamps** [comment]
Total!!!!
