### ISSUE TITLE
Mocha e Promises

### ISSUE THREAD

**Issue by filipedeschamps** [filipedeschamps/cep-promise#7]
Faz um bom tempo que não utilizo mocha+chai+promises, imagino que muita coisa mudou.

Alguém recomenda a melhor forma atual de abordar esse cenário?

**Comment by glundgren93** [comment]
O que você acha de utilizar o chai-as-promised? 

[](https://github.com/domenic/chai-as-promised/)

**Comment by filipedeschamps** [comment]
Show @glundgren93 feito :+1: 

Fiz referência ao seu username no commit https://github.com/filipedeschamps/cep-promise/pull/8/commits/82b5d5ecedd27b8c825fba2a049788ae5c17d3a6
