### ISSUE TITLE
DevDependencies desatualizadas

### ISSUE THREAD

**Issue by chrisbenseler** [filipedeschamps/cep-promise#72]
Rodar npm outdated na cli, dá o seguinte output:

![screenshot from 2016-12-08 13-20-07](https://cloud.githubusercontent.com/assets/1225447/21015429/170f3b8c-bd49-11e6-99aa-67df58b96b06.png)

muitas dependências estão desatualizadas.
Não seria uma boa dar um update nelas?

**Comment by chrisbenseler** [comment]
Atualizei no meu fork o package.json com as últimas versões desses pacotes, dei um npm update, buildei novamente e rodei os testes. Todos passaram.

**Comment by filipedeschamps** [comment]
@chrisbenseler please faz um PR 👍

**Comment by chrisbenseler** [comment]
Feito.
