### ISSUE TITLE
Atualizar README com instruções para uso no browser.

### ISSUE THREAD

**Issue by lucianopf** [filipedeschamps/cep-promise#77]
O tempo ta corrido então vou deixar aqui a ideia e se sobrar um tempo e ngm tiver feito eu faço :smile: 

Adicionar informações referentes ao uso da biblioteca nos navegadores no README:

1. Usando npm install mesmo.
2. Usando a [Unpkg](https://unpkg.com/) como CDN ou apontando direto pro file https://unpkg.com/cep-promise@2.0.3/dist/cep-promise-browser.min.js ou fazendo a configuração correta (tem que estudar direitinho o 'browser' do package.json pra não conflitar com a  config atual. [ref](https://github.com/defunctzombie/package-browser-field-spec))
3. Criar um package no registry do bower.

[Cdnjs](https://cdnjs.com/) tbm é uma opção, mas como tem que criar a issue lá pra eles disponibilizarem acho mais chato de fazer. =/

**Comment by jhonnymoreira** [comment]
@lucianopf nós aqui do Gaveteiro estamos utilizando a lib no browser e enfrentamos problemas na hora de inserir a biblioteca por falta de instrução, porém, conseguimos ao analisar melhor tudo.

Gostaríamos de pegar essa issue e fazer o que foi descrito. Tudo bem?

**Comment by lucianopf** [comment]
Perfeitamente @jhonnymoreira !!
Contribuições são sempre bem vindas!!

Só não fiz ainda essa documentação por falta de tempo mesmo, mas é algo que certamente irá ajudar muitas pessoas!! 😄 

Precisando de ajuda é só me chamar! 🤓

**Comment by jhonnymoreira** [comment]
@lucianopf perfeito! Essa semana já faço um patch pra isso. E obrigado por se disponibilizar!

**Comment by filipedeschamps** [comment]
Caramba que massa! Obrigado pela ajuda @jhonnymoreira 👍

**Comment by lucianopf** [comment]
@jhonnymoreira lembrei que a alguns dias eu tinha criado uma [issue no cdnjs](https://github.com/cdnjs/cdnjs/issues/10926) pedindo pra add a lib, mas nem cheguei a fazer o PR dela não.

Aparentemente é bem simples de fazer o PR pra eles. [Exemplo](https://github.com/cdnjs/cdnjs/pull/11051)

**Comment by lucianopf** [comment]
@filipedeschamps vc ta acompanhando as estatisticas?  [Link](https://npm-stat.com/charts.html?package=cep-promise&from=2015-12-01&to=2017-04-20)
🎉 👏 
Se encaixa em basicamente todos os requisitos pra prioridade no CDNJS! =D

**Comment by filipedeschamps** [comment]
Sim!! Ta pegando um volume bizarro!!!

E não conhecia essa pagina com gráficos, animal!!

**Comment by filipedeschamps** [comment]
Belo trabalho galera 👍

**Comment by Luc45** [comment]
Opa, alguma novidade em relação à documentação sobre como usar esta library diretamente no browser, sem necessidade de compilar com npm ou similar? Obrigado!
