### ISSUE TITLE
Importar em projeto Angular 2

### ISSUE THREAD

**Issue by chrisbenseler** [filipedeschamps/cep-promise#78]
@filipedeschamps estou brincando com Angular 2 pensei usar o cep-promise num teste.

Existe uma forma de dar um import nele?
`import cep from 'cep-promise'`
não funciona, diz que não existe o módulo. Testei, meio que no chute, com
`import cep from 'cep-promise/dist/cep-promise'`
mas não rola também.

Agora, usando um require, funciona normalmente. Exemplo:

```
let cep = require('cep-promise/dist/cep-promise');
...
export class SearchComponent implements OnInit {
  ngOnInit() {
  	cep('04477-100')
  	.then( data => {
  		console.log(data)
  	})
  }
}
```

Eu nem sei se isso é uma issue na real, se tem alguma coisa a ver com o TypeScript, se é algo relacionado com o babelify.

**Comment by lucianopf** [comment]
@chrisbenseler 
E se vc usar a importação assim:
`import * as cepModule from  'cep-promise'`
Não rola não?!
Se for, assim acho que vc chama assim: `cepModule.cep('127836213')`

**Comment by chrisbenseler** [comment]
Não rolou @lucianopf 

search.component.ts (3,28): Cannot find module 'cep-promise'.

Na raiz da pasta node_modules/cep-promise/ não tem nenhum .js, só tem os .MD, o LICENSE e o package.json
Pastas, só tem a content/, coverage/ e dist/

**Comment by lucianopf** [comment]
mas o package.json aponta pro dist direitinho, isso que usualmente é identificado. =/
Por isso funciona no node de boa, tenta fazer isso usando a versão web pfv. =/

**Comment by lucianopf** [comment]
@chrisbenseler 
Mano, usando em um projeto react meu aqui eu consegui acessar ele assim agora:
`import { default as cep } from 'cep-promise'`

**Comment by chrisbenseler** [comment]
Mesmo problema aqui. Se quiser tentar reproduzir, tendo o angular-cli instalado ai no environment (fiz do 0 aqui, um projeto blank, pra ver se tinha algo a ver)

na cli:
```
ng new testeceppromise
npm install --save cep-promise

```

fazer o import no app.components.ts
`import { default as cep } from 'cep-promise';`

na cli:
`ng serve`

nesse projeto novo, se troco o import por aquele require, também funciona.
Estou com a versão 2.0.3 da cep-promise e versão 6.4.0 do node.

**Comment by lucianopf** [comment]
Eita porrinha complicada essa de Angular2 e TS! rsrs

Pera que vou invokar um amiguinho aqui pra te ajudar! hahaha

**Comment by lucianopf** [comment]
@Petronetto consegue dar um help pro camarada aí?! rsrs

**Comment by chrisbenseler** [comment]
@lucianopf to achando que tem alguma coisa a ver com o compilador do TypeScript, mas é um chute. Vou dar uma googlada.

**Comment by Petronetto** [comment]
@chrisbenseler se você está usando o angular-cli `const cep = require('cep-promise')`  vai funcionar.

**Comment by Petronetto** [comment]
Criei um [Pull Request](https://github.com/filipedeschamps/cep-promise/pull/79) com a definição, com isso o `import { default as cep } from 'cep-promise'` vai funcionar.

**Comment by filipedeschamps** [comment]
Open source = ❤️

**Comment by chrisbenseler** [comment]
@Petronetto com o require estava funcionando mesmo, eu até estava usando assim. Vou dar uma estudada nessa questão, junto com teu PR, pra ver se entendo o que mudou. Obrigado!

**Comment by Petronetto** [comment]
@chrisbenseler em linhas gerais, quando você usa o require, simplesmente está pegado algo do seu node_modules e jogando para dentro de uma constante qualquer, o TS não vai fazer nenhuma validação e não vai te dar autocomplete nem nada do tipo.
Quando você usa o import o TS vai procurar um arquivo de definição, para que ele possa fazer a validação. Com a definição que criei por exemplo, o TS sabe que retorna uma promise, com isso ele pode ter dar o autocomplete e sabe também que aceita string ou number como parâmetros de entrada, se você tentar fazer `cep(true)`, por exemplo, o TS vai acusar um erro e te dizer que boolean não é um parâmetro de entrada válido.

Qualquer dúvida estamos ai.

**Comment by chrisbenseler** [comment]
Valeu @Petronetto 

Assim que for pro npm a atualização, testo essas mudanças todas.

**Comment by filipedeschamps** [comment]
@chrisbenseler acabei de fazer o release 👍  está na `2.0.4`

**Comment by duuhleon** [comment]
Olá boa tarde, tem como fazer a atribuição pra uma variavel??? estou tentando aqui mas não está tão fácil

let address = cep(postalCode).then(console.log);
