### ISSUE TITLE
Problema entre "npm run build" para o bower e .gitignore

### ISSUE THREAD

**Issue by filipedeschamps** [filipedeschamps/cep-promise#86]
@jhonnymoreira tudo bem?

Fiz o merge e iria fazer o release, mas ao rodar local o `npm run build` notei duas coisas:

1. Gerou um diff dos binários finais de distribuição (não sei porque)
2. Listou arquivos untracked de `dist`. Pelo que eu entendo, eles deveriam estar no .gitignore, correto? Ou precisam estar commited?

Segue print do `git status` logo após o `npm run build` da branch `master` limpa:

![image](https://cloud.githubusercontent.com/assets/4248081/25482887/fe453c92-2b29-11e7-9aef-8a38d53bcf0f.png)

**Comment by lucianopf** [comment]
Então.. pelo que andei futucando no bower eu tbm não consegui engatilhar o npm run build.

Daí acredito que o @jhonnymoreira achou que a melhor solução seria versionar ao menos os arquivos do browser como é feito por exemplo no [Bootstrap](https://github.com/twbs/bootstrap/tree/v4-dev/dist/js).

Eu acho uma falha terrível no Bower mas acredito que esse é o jeito padrão de se publicar pacotes no registry deles. =/

Acho que da pra fazer um ignore melhorzinho tipo:
```
dist
!dist/cep-promise-browser[!.min]js
```
(Nunca usei essa opção da lista não, mas acho que funciona! hahaha

**Comment by lucianopf** [comment]
A vantagem de fazer dessa forma é que pode-se acessar esses arquivos como CDN.

- RawGit: [CepPromise.min.js](https://cdn.rawgit.com/filipedeschamps/cep-promise/68a0e48c/dist/cep-promise-browser.min.js)

- Github raw content: [CepPromise.min.js](https://raw.githubusercontent.com/filipedeschamps/cep-promise/master/dist/cep-promise-browser.min.js)

**Comment by jhonnymoreira** [comment]
@lucianopf @filipedeschamps já criei um registro no `bower/registry`. To esperando mais um tempinho pra ver qq tá rolando, pq a pasta `dist/` não tá sendo reconhecida. [=

**Comment by filipedeschamps** [comment]
Show!

Acho que do .gitignore é o que o @lucianopf falou mesmo 👍

**Comment by lucianopf** [comment]
Fiz o PR #87 pra minimizar esses efeitos =D

(O yarn é pq ele realmente ta bem melhor que o atual NPM 😞 )

**Comment by filipedeschamps** [comment]
Show, tudo ajustado!

Fiz release da versão `2.0.5`, belo trabalho pessoal 👍
