### ISSUE TITLE
500 Stars!!!

### ISSUE THREAD

**Issue by lucianopf** [filipedeschamps/cep-promise#89]
🎉 🎈 🎊  500 stars galeraaaa!!! 🎊 🎈 🎉 

![screen shot 2017-05-02 at 9 58 44 am](https://cloud.githubusercontent.com/assets/8251208/25621008/20b352e4-2f1e-11e7-9431-a728faa3ee66.png)

Parabéns @filipedeschamps e todos os contribuidores do projeto!!!

**Comment by filipedeschamps** [comment]
Hooray!!! 👍 

Os stats também estão crescendo bizarramente 

https://npm-stat.com/charts.html?package=cep-promise&from=2016-04-01&to=2017-05-01

> 1,574 downloads in the last month

Parabéns a todos os envolvidos!!!

**Comment by MarcoWorms** [comment]
⚠️⚠️⚠️ Atenção ⚠️⚠️⚠️

✅ A biblioteca📚de javascript cep-promise™ atingiu 👉500 🌟estrelas🌟🌟 de popularidade💁 no site de codificação💾 colaborativa 👯‍♂️GitHub 👯‍♂️👯‍♂️.

✅ Se você 🙋‍♂️ precisar buscar🔍🔍🔍 um 🛣endereço🇧🇷 utilizando um 👉CEP👈 ❗️não se esqueça❗️ de utilizar a 📚biblioteca📚 mais 💅 cheirosa do oeste 🌎
