### ISSUE TITLE
Dúvida sobre a busca do CEP

### ISSUE THREAD

**Issue by cmargulhano** [filipedeschamps/cep-promise#93]
Primeiramente parabéns pelo componente.

Tenho uma dúvida.
Por que buscar o CEP em dois lugares?

https://apps.correios.com.br/SigepMasterJPA/AtendeClienteService/AtendeCliente
https://viacep.com.br/ws/12236896/json/

Agradeço a atenção,
Cláudio

**Comment by lucianopf** [comment]
Opa @cmargulhano que bom que vc curtiu! =D

Então, o principal objetivo de usar múltiplas fontes é para melhorar a performance e a disponibilidade do serviço.

Assim que se inicia a requisição de um CEP a biblioteca inicia uma corrida pra ver quem resolve primeiro e assim que uma resposta é obtida é enviada ao usuário.

Vc tem alguma objeção ou ideia a acrescentar nesse modelo?

Estamos totalmente abertos a discussões! ^^

**Comment by cmargulhano** [comment]
Na verdade é um modelo bem legal, porém acho que poderia ser configurado para escolhar a fonte da pesquisa. Oficialmente os Correios "deveriam" manter o serviço ativo. Já o ViaCEP não é uma fonte oficial e, um dia, por algum motivo qualquer ele poderia sair do ar.

**Comment by lucianopf** [comment]
Acho interessante optar por consultar apenas o Correios, pois acredito que a confiabilidade dos dados deles é maior, mas quanto ao ViaCEP cair isso não será um problema, pq sempre existirá outro fallback.

A lib só não irá resolver um cep caso todos os seus sources tenham falhado na busca pelo CEP, bem no esquema de fallback msm! ^^

A ideia ao adicionar o ViaCEP era adicionar outras fontes tbm, pra que a disponibilidade fosse ainda maior e o tempo de resposta o melhor possível 🤔 

Vc vê a necessidade real de restringir a resposta apenas para uma fonte?

**Comment by cmargulhano** [comment]
Minha única preocupação é de colocar um sistema em produção e depois parar de funcionar por que o ViaCEP ficou fora do ar.

Seria legal:
Se busca nos Correios estiver OK então retorna CEP
senão busca em fonte 1
senão busca em fonte N

**Comment by cmargulhano** [comment]
Isso poderia ser uma opção da biblioteca :)

**Comment by lucianopf** [comment]
Então, na verdade, se qualquer um das fontes parar a lib vai continuar tentando resolver via outras fontes, por exemplo:

cep(29065250) -request-> ViaCEP (29065250) -badResponse-> Correios (29065250) -> OK.

A diferença é que não é em série assim, é em paralelo mesmo, pra que quando uma responder primeiro essa será a resposta, agora se uma falhar primeiro isso não impede as demais de concluir e entregar a resposta correta.

**Comment by filipedeschamps** [comment]
@cmargulhano o problema de ser sequencial é que se o serviço dos Correios estiver engargalado, você vai ter que definir um timeout para poder pular para o próximo provider e o reflexo que você vai perceber no seu sistema é que ele de repente ficou mais lerdo.

Isso maximiza linearmente conforme você for adicionando mais providers, sendo que no modelo atual, quanto mais providers, mais rápido você vai ter o resultado.

**Comment by olegon** [comment]
@cmargulhano Eu acho interesse não ter que me  preocupar com a fonte onde os dados são buscados e deixar essa preocupação para a comunidade, a não ser que haja uma regra no meu negócio sobre essas fontes, claro. Caso surja um serviço melhor, um serviço deixe de funcionar ou se houver uma atualização de um dos serviços tornando a antiga versão inutilizável, a própria comunidade vai lançar uma nova versão e basta eu manter a biblioteca atualizada. ;) Esse é um grande poder de uma comunidade ativa!

**Comment by filipedeschamps** [comment]
Pessoal, estou fechando essa issue, qualquer coisa podemos reabrir 👍
