### ISSUE TITLE
FETCH não retorna dados

### ISSUE THREAD

**Issue by medeirosrafael** [filipedeschamps/cep-promise#94]
Boa tarde. Hoje o viacep estava fora do ar, e acabei encontrando esse projeto. Gostei bastante da ideia. Meu projeto é em Angular2.

O problema é que toda requisição feita para os correios dá erro. Mesmo retornando dados (possível de ser visualizado no dev-tools). Aparentemente, o problema é que a requisição fetch feita com "mode: no-cors", retorna uma resposta com ok = false e type = opaque, sem header, sem body, sem nada..

O que eu posso fazer para resolver isso?

**Comment by lucianopf** [comment]
Boa noite amigo! =D

A verdade é que a lib começou com a ideia de resolver o problema no back-end, com Node, e com o tempo a gnt foi progredindo ela até chegar no front com o cliente web, o problema é que o service dos correios realmente não aceita requisições no browser, devido a política de CORS adotada.

Como fica explicito [aqui](https://github.com/filipedeschamps/cep-promise/blob/master/src/services/correios-browser-mock.js).

Pra contornar esse problema uma boa solução seria criar um nano serviço que apenas resolvesse ceps, daí vc nunca mais teria problemas de CORS. 🤔 

Por exemplo, criar uma função no [webtask.io](webtask.io) que resolva os ceps.

Vou criar uma função de exemplo aqui pra caso vc queira ter uma guia..

(Caso vc tenha alguma ideia de como resolver esse problema ao nível de lib, nós ficaremos muito felizes em discutir isso e melhorar o `cep-promise`

**Comment by lucianopf** [comment]
# Exemplo

URL: https://wt-1e0e66e290be8bceb5902198c7a1999a-0.run.webtask.io/cep-promise/29065250

Code:
```
var express    = require('express');
var Webtask    = require('webtask-tools');
var bodyParser = require('body-parser');
var app = express();
const cep = require('cep-promise')

app.use(bodyParser.json());

app.get('/:cep', function (req, res) {
  if (req.params.cep) {
    return cep(req.params.cep)
      .then(response => res.json(response))
      .catch(e => res.send(500, e))
  } else {
    res.send(500, 'No cep provided')
  }
});

module.exports = Webtask.fromExpress(app);

```

**Comment by medeirosrafael** [comment]
@lucianopf, boa noite. Obrigado pelas explicações detalhadas e exemplos. Entendi a questão, como era algo meio urgente, eu acabei solucionando fazendo um "fallback" na mão, quando a requisição retorna erro do viacep, faço uma consulta para o meu servidor, que por sua vez vai faz a requisição para os correios. Não é excelente, mas, me atendeu. Minha necessidade era exclusivamente para front-end.
Mais uma vez, obrigado pela atenção.

**Comment by filipedeschamps** [comment]
Precisamos de mais providers de cep :)

2017-10-03 22:35 GMT-03:00 medeirosrafael <notifications@github.com>:

**Comment by alexandremaeda** [comment]
Uso bastante o [postmon](http://postmon.com.br/).

**Comment by lucianopf** [comment]
Interessante hein @alexandremaeda !!

[Código com os services deles](https://github.com/PostmonAPI/postmon/blob/master/CepTracker.py)

**Comment by alexandremaeda** [comment]
Não parei de ver a fonte deles. É a mesma que vocês então...

**Comment by lucianopf** [comment]
Marromens, eles usam o cep tbm, mas de outra maneira (que talvez tenha `cors: *`) e usam outro que a gnt não usa. 

Acho válido adicionar como service pra testar, o que acha @filipedeschamps ? 🤔

**Comment by filipedeschamps** [comment]
Ah que massa!

Eu integraria eles com certeza, ainda mais por utilizarem a outra abordagem
de consultar o site mobile dos correios, é um bom fallback :)

**Comment by lucianopf** [comment]
🤕 

Pq diabos a galera não mete um `*` hein?! 

![screen shot 2017-10-16 at 11 26 53 am](https://user-images.githubusercontent.com/8251208/31620356-08f217e2-b265-11e7-84c9-599298ba2277.png)

**Comment by leogregianin** [comment]
Quem acham de implementar o cepaberto.com ?

**Comment by lucianopf** [comment]
Curti hein mano! =D

Me parece bem simples de usar!

```
curl http://www.cepaberto.com/api/v2/ceps.json?cep=40010000 -H \
'Authorization: Token token="37bfda18fd4b423cdb6748d14ba30aa6"'
```

**Comment by filipedeschamps** [comment]
Suporte ao `Cep Aberto` adicionado pelo @lucianopf na versão `2.0.6` 👍 👍 👍 👍 👍 👍 👍
