### ISSUE TITLE
Como usar no AngularJS

### ISSUE THREAD

**Issue by humbertosales** [filipedeschamps/cep-promise#96]
Prezados, não consegui captar como usar esta excelente biblioteca no AngularJS...

Poderiam explicar?

**Comment by lucianopf** [comment]
Opa @humbertosales , beleza?

Se não me engano AngularJS é a 1.x, correto?! E é apenas uma lib de front, correto?

Existem diferentes formas de usar a biblioteca, mas pra brincar um pouquinho eu subi uma página estática já com o cep-promise carregado pra vc brincar no console [AQUI](http://cep-promise.surge.sh/)

Dps de carregada a dependência o window vai ter uma nova função chamada cep que retorna as informações assincronamente.

Um exemplo de uso seria `cep(29065250).then(res => console.log(res))`

Não há diferenças quando usado com Angular, podendo ser chamado em qualquer lugar já que a função está disponível no objeto window.

A sua dúvida era realmente sobre o front do AngularJS ou sobre Angular 4 em diante?

**Comment by MarcoWorms** [comment]
@humbertosales se não conseguir, divide o código do que vc ta fazendo com a gente pra podermos te ajudar melhor. Se for um repo aqui no github então melhor ainda :)

**Comment by Oda2** [comment]
@MarcoWorms coloca no index (https://cdn.rawgit.com/filipedeschamps/cep-promise/44083ee4/dist/cep-promise-browser.min.js) e em qualquer controller só chamar ``cep(17690000).then(res => console.log(res))``

**Comment by filipedeschamps** [comment]
@humbertosales espero que você tenha conseguido usar no AngularJS como esperado.

@lucianopf @MarcoWorms @Oda2 muito obrigado pela ajuda, vocês são sensacionais!
