### ISSUE TITLE
Erro ao buscar no CEP Aberto

### ISSUE THREAD

**Issue by kavalcante** [filipedeschamps/cep-promise#98]
Ao fazer a busca, ela retorna com sucesso, porém no console é reportado erro por parte do CEP Aberto de CORS. Além de dar 404.

![screenshot from 2017-11-25 19-01-15](https://user-images.githubusercontent.com/13931503/33235242-2c9118f8-d21b-11e7-8a86-557a9871cd21.png)

É no client-side, não cheguei a testar no server-side.

**Comment by lucianopf** [comment]
Opa @kavalcante, to tentando inspecionar o seu erro aqui mas não estou conseguido, tem como me fornecer algumas informações adicionais pra eu tentar replicar e consertar?

1 - Como foi o processo de instalação?
2 - Tem certeza que está usando o `cep-promise-browser.js` como source?
3 - Vc atualizou a dependencia ou isso foi ao adicionar ela no seu projeto?

**Comment by kavalcante** [comment]
Opa Luciano, eu utilizo Vue.js. O que fiz foi simplesmente fazer o import:

```js
import cep from 'cep-promise';
```

E depois chamei a função via um method, dessa maneira:

```js
methods: {
  searchCep(zipcode) {
    return cep(zipcode);
  },
},
```

E nesse projeto em especifico foi só adicionar no projeto. Inclusive por isso abri a Issue, pois isso não está acontecendo com as implementações do Correios e Via CEP (tanto é que ele retorna com sucesso).

Eu tentei criar um Fiddle, mas não consegui :(

**Comment by lucianopf** [comment]
Foi utilizando o npm então mesmo, né?

Entendi.. existe a chance do seu import não estar pergando a versão dentro da `dist/cep-promise-browser.js`?

Tem como vc testar importando manualmente o caminho pro arquivo específico para versões do browser?

**Comment by kavalcante** [comment]
Sim, foi através do NPM.

Testei aqui e é isso mesmo que está acontecendo. Quando fiz o apontamento para:
```js
import cep from 'cep-promise/dist/cep-promise-browser.min';
```

O erro parou. E quando voltei para o normal, o erro continua.

**Comment by lucianopf** [comment]
O bundle que vc ta usando não é o correto de se utilizar na no front, dado ao seu tooling e a forma como vc gera o seu JS no front vc está pegando a lib de Node e injetando dentro do seu bundle.

É uma peculiaridade da biblioteca que nós precisamos documentar. =(

Vc ta usando o que para transpilar o código e gerar o seu bundle?

Vou dar uma investigada um pouco mais afundo pra ver se tem algo que eu consiga fazer pra detectar quando a lib é importada pra ser adicionada num bundle.

(Se não me engano no lado do webpack tem como vc criar um alias pra uma dependência apontando um arquivo, acho que isso já te ajudaria 🤔 )

**Comment by MarcoWorms** [comment]
@lucianopf creio que vc não consiga fazer isso dinamicamente, na [pagarme-js](https://github.com/pagarme/pagarme-js) a gente também teve que fazer bundles separados pra borwser e node :P

**Comment by lucianopf** [comment]
Puts.. =(

Então é alterar a documentação mesmo 😢

**Comment by kavalcante** [comment]
Eu utilizo Webpack mesmo. Então, o que me estranha, é que nas versões anteriores (quando era ViaCEP e Correios), isso já era feito automaticamente. Uma das nossas aplicações inclusive está com essa versão anterior implementada.

Outra coisa que aconteceu, mas essa ainda não é certeza, é que deu alguns erros importando dessa maneira (parcial). Eu não cheguei a ver direito, mas era algo como "O correios não aceita requisições via browser". Vou checar isso melhor, e vejo se é de fato um bug. Qualquer coisa abro outra issue.

**Comment by lucianopf** [comment]
Caraca mano, vc ta certo, de alguma forma a versão 2.0.5 pra baixo não reclamava disso, o que é bizarro! 🤔 

Vou continuar brincando aqui pra ver se consigo replicar esse comportamento bizarro dnv! rsrs
Inserir o novo service alterou um cadinho como os outros services funcionam, inclusive achei um errinho que ligou novamente um dos services e pode ser isso que tava fazendo não acusar o erro de CORS.

Quanto ao seu segundo ponto eu não consegui replicar de forma alguma =(

![screen shot 2017-11-29 at 9 58 00 am](https://user-images.githubusercontent.com/8251208/33374134-0746bb1a-d4ec-11e7-93e5-88966c37a736.png)
![screen shot 2017-11-29 at 9 58 12 am](https://user-images.githubusercontent.com/8251208/33374143-0b34b1d2-d4ec-11e7-88b8-75d62b560c14.png)

**Comment by lucianopf** [comment]
Rapaz.. eu odeio admitir a derrota mas me parece ser o único jeito.. 

O motivo pelo qual estava funcionando é realmente pq antes não estava funcionando... hehehe

Vc tem duas formas de consertar isso no lado do cliente:

1 - Webpack alias para `/node_modules/cep-promise/dist/cep-promise-browser.min.js`
2 - Baixar usando bower, mas eu nem sei se está com a versão mais atualizada. @filipedeschamps 

Vou adicionar esses passos no README pra ajudar a galera que tiver o mesmo problema que vc.

**Comment by kavalcante** [comment]
Beleza @lucianopf, obrigado pela ajuda!

**Comment by lucianopf** [comment]
@kavalcante tem como confirmar se a issue foi resolvida fazendo favor irmão?

**Comment by MarcoWorms** [comment]
@kavalcante ta resolvido? podemos fechar essa issue? :)

**Comment by danielsalles** [comment]
Tive o mesmo erro aqui.

**Comment by MarceloPrado** [comment]
Estava com o mesmo erro. Importando diretamente a distribuição de browser corrigiu.

`import cepPromise from 'cep-promise/dist/cep-promise-browser.min';`

**Comment by kavalcante** [comment]
Desculpe a demora em retornar com isso. Tentei a implementação parcial, porém meu problema é que a aplicação que eu trabalho é SSR. Quando o Nuxt tenta fazer o import, o window que é requerido na versão do browser não existe. E se eu importo a versão normal, dá aquele erro de CORS.

Talvez a minha única solução seja, ou deixar do jeito que está, apenas buscando na ViaCep, ou criando um endpoint rest via back-end para lidar com as requisições, o que eu particularmente acho extremamente ruim, pois vou ter que fazer um request, que faz outros dois request's.

Outro problema que vi o browser notificar é que o CepAberto não possui HTTPS. Não sei se isso é um ponto negativo e se implica em alguma coisa.

**Comment by kavalcante** [comment]
Acredito que esse problema seja na implementação da própria CepAberto, não sei se isso pode ser um erro da lib, pelo menos não me parece ser o caso.

Além disso, eu utilizo `axios` para realizar a requisição.

**Comment by lucianopf** [comment]
O problema em si foi resolvido importando o arquivo com a build específica para web, vou continuar tentando simplificar isso, mas enquanto isso é a forma que temos =/
